import type { Metadata } from "next"
import { TerrainPage, type TerrainCopy } from "@/components/terrain/terrain-page"

/**
 * BRAND — le terrain marques & entreprises.
 *
 * Même page que THE ROOM, au caractère près : même HTML, même CSS, même
 * JavaScript, donc le canvas bokeh, la tournée épinglée, le comparateur et
 * l'accordéon sont identiques. Seul le texte change, par surcharge du
 * dictionnaire.
 *
 * Les clés non surchargées héritent du texte de THE ROOM : ce sont celles
 * qui parlent du studio, du prix ou de la méthode, et qui sont vraies quel
 * que soit le terrain — c'est exactement ce que l'unification affirme.
 */

export const metadata: Metadata = {
  title: "BRAND — L'architecture narrative pour les marques et les entreprises",
  description:
    "On vous compare au prix parce que rien ne dit qui vous êtes. L'architecture narrative lit ce que votre marque raconte aujourd'hui et donne les mouvements qui la sortent du rayon.",
}

const COPY: TerrainCopy = {
  slug: "marques-entreprises",
  wordmark: "BRAND",
  fr: {
    "ex.eyebrow": "Un cas",
    "ex.title": "Ce qu'on a livré à LOAM, et ce que ça a changé.",
    "ex.head": "Architecture narrative · Marques",
    "ex.house": "Maison LOAM",
    "ex.lead": "LOAM, mobilier de bureau sur mesure, douze ans, quatorze personnes. Le nom est changé, les livrables ne le sont pas.",
    "ex.1.n": "Pièce 01",
    "case.eyebrow": "Ce que ça donne, ailleurs",
    "case.title": "Trois maisons qui ont tranché.",
    "case.lead": "Aucune n'a été construite par nous. Toutes les trois ont fait, à leur échelle, ce que cette Architecture fait à la vôtre.",
    "case.1.name": "Nike",
    "case.1.refuse": "A refusé de vendre des chaussures — elle vend une conviction sur le dépassement de soi.",
    "case.1.risk": "Parler de sport plutôt que de produit, quand chaque concurrent vantait l'amorti ou la respirabilité.",
    "case.1.win": "On reconnaît une publicité Nike avant même d'avoir vu le logo.",
    "case.2.name": "Coca-Cola",
    "case.2.refuse": "A refusé de se fragmenter en sous-marques concurrentes.",
    "case.2.risk": "Résister à la tentation de décliner, segmenter, moderniser le nom — pendant un siècle.",
    "case.2.win": "Ce qui ne change jamais est devenu la preuve même de la marque.",
    "case.3.name": "Picard",
    "case.3.refuse": "A refusé de concurrencer les primeurs sur le frais.",
    "case.3.risk": "Vendre fièrement ce que la plupart des enseignes cachent ou traitent comme un pis-aller.",
    "case.3.win": "Impossible à confondre avec un simple supermarché.",
    "deliv.eyebrow": "Ce que vous recevez, précisément",
    "deliv.title": "Les six pièces, pour votre entreprise.",
    "deliv.lead": "Le même document que pour n'importe quelle maison, mais rien de générique dedans.",
    "deliv.1.t": "La plateforme",
    "deliv.1.d": "Ce que votre entreprise défend, au-delà du produit qu'elle vend — la conviction qui doit tenir même quand la gamme change.",
    "deliv.2.t": "Le diagnostic",
    "deliv.2.d": "Votre site, votre plaquette commerciale, votre argumentaire dépouillés — l'écart entre ce que dit le commercial et ce que dit le site.",
    "deliv.3.t": "La carte",
    "deliv.3.d": "Vos concurrents directs disséqués phrase par phrase, et le terrain qu'aucun d'eux n'occupe encore.",
    "deliv.4.t": "Les décisions",
    "deliv.4.d": "Les mouvements à faire avant toute refonte visuelle ou toute campagne — dans l'ordre, avec ce que chacun coûte.",
    "deliv.5.t": "Les playbooks",
    "deliv.5.d": "Ce que dit un commercial en rendez-vous, ce que répond le service client à un mécontent, ce qu'un nouvel embauché doit comprendre dès sa première semaine.",
    "deliv.6.t": "Le langage",
    "deliv.6.d": "Le vocabulaire que toute l'entreprise emploie — des plaquettes aux réponses email — pour ne plus jamais sonner comme le concurrent d'à côté.",
    "ex.1.k": "La plateforme de marque",
    "ex.1.b": "Une raison d'être en une phrase — « le mobilier qu'on ne remplace pas » — un positionnement, trois valeurs formulées en refus plutôt qu'en adjectifs, et un ton de voix avec ses exemples. Neuf pages.",
    "ex.1.pk": "Ce que ça a changé",
    "ex.1.pv": "Les trois valeurs tenaient sur un mur de l'atelier. Deux mois plus tard, la deuxième a servi à refuser une commande de 40 000 € en aggloméré — la première fois que le refus était justifiable devant l'équipe.",
    "ex.2.n": "Pièce 03",
    "ex.2.k": "La carte du champ",
    "ex.2.b": "Cinq concurrents, leur phrase d'accueil citée mot pour mot, ce que chacun revendique, et le relevé des mots partagés. Le constat : « sur mesure » chez trois d'entre eux, « artisanal » chez trois aussi, le délai revendiqué par aucun.",
    "ex.2.pk": "Ce que ça a changé",
    "ex.2.pv": "LOAM a cessé d'employer « sur mesure », présent onze fois sur son site. Le mot a été remplacé par le délai — le seul terrain que le panel laissait libre, et le seul qu'ils pouvaient tenir : ils sont les seuls à sécher en interne.",
    "ex.3.n": "Pièce 04",
    "ex.3.k": "Les décisions",
    "ex.3.b": "Quatre mouvements ordonnés. Le premier : remplacer la phrase d'accueil par le refus, avec la formulation exacte à employer. Chacun chiffré — ce qu'il coûte, ce qu'il fait perdre, dans quel ordre le faire.",
    "ex.3.pk": "Ce que ça a changé",
    "ex.3.pv": "Le mouvement 1 était chiffré à une perte estimée de 25 % des demandes entrantes. Ils l'ont pris. Les demandes ont baissé ; le taux de signature a monté, parce que ceux qui restaient n'appelaient plus pour comparer un délai.",
    "ex.4.n": "Pièce 05",
    "ex.4.k": "Les playbooks",
    "ex.4.b": "Cinq playbooks — vente, contenu, réseaux, support, recrutement. Celui de la vente contient les trois objections réelles relevées dans leurs devis perdus, et la réponse à chacune. Celui du recrutement nomme le trait disqualifiant.",
    "ex.4.pk": "Ce que ça a changé",
    "ex.4.pv": "Le commercial arrivé en mars a été opérationnel sans formation : il a lu le playbook et repris les formulations. Son premier devis n'a pas eu besoin d'être relu — c'est la première fois en douze ans.",
    "ex.foot": "Six pièces livrées. Quatre montrées ici.",
    "tour.out": "Vous avez déjà tout ce qu'il faut. Ce qui manque, c'est une identité pour le rendre visible.",
    "hero.kicker": "Architecture narrative · Marques & entreprises",
    "mq.1": "Marques",
    "mq.2": "Entreprises",
    "mq.3": "Studios",
    "mq.4": "Cabinets",
    "mq.5": "Éditeurs",
    "mq.6": "Ateliers",
    "hero.tag": "Un concurrent deux fois moins bon<br/><b>signe les contrats qui étaient les vôtres.</b>",
    "man.eyebrow": "Le constat",
    "man.body": "<b>Un concurrent deux fois moins bon que vous signe les contrats qui auraient dû être les vôtres.</b> Il ne travaille pas mieux. Il ne livre pas mieux. Il se raconte mieux — et sur un marché où personne ne peut juger la qualité avant d'acheter, c'est le seul critère qui tranche.",
    "man.body2": "Votre produit tient, vos clients reviennent. Mais on vous demande un devis comparatif avant même de vous avoir écouté, parce que rien dans ce que vous dites ne dit ce que vous refusez. <em>Votre récit n'a jamais été écrit.</em>",
    "focus.eyebrow": "La différence",
    "focus.title": "Communiquer, ou tenir une position.",
    "focus.lead": "La même marque, deux réalités. Prenez la poignée et tirez : à gauche on communique sans savoir quoi défendre, à droite la position est écrite et toute l'équipe la tient.",
    "focus.bad.tag": "Une marque qui communique",
    "focus.bad.big": "Chaque prise de parole repart de zéro. Personne ne sait ce qu'on revendique, ni ce qu'on refuse.",
    "focus.good.tag": "Une marque qui tient une position",
    "focus.good.big": "La position est écrite. N'importe qui dans l'équipe sait ce qu'on revendique et ce qu'on refuse. Tout se ressemble, sans se répéter.",
    "faq.title": "Ce que les dirigeants nous demandent.",
    "faq.1.q": "Pourquoi pas une agence au mois ?",
    "faq.1.a": "Parce qu'au bout de deux ans vous aurez payé environ 30 000 € sans rien garder. Ici vous payez 2 900 € une fois, et le document vous appartient.",
    "faq.2.q": "Mes commerciaux vont-ils vraiment s'en servir ?",
    "faq.2.a": "C'est ce que le playbook vente est fait pour. Il contient vos trois objections réelles avec la réponse à chacune, la formulation exacte quand on demande un devis comparatif, et ce qu'on ne concède jamais. Un commercial qui arrive le lundi peut l'utiliser à son premier rendez-vous — c'est le test qu'on s'applique.",
    "faq.3.q": "Combien de temps ça prend, de mon côté ?",
    "faq.3.a": "Une heure pour le questionnaire, en une ou deux fois. Puis rien pendant douze jours : nous dépouillons vos supports et ceux de vos concurrents sans vous solliciter. Une heure encore au jour 20 pour relire le document ensemble.",
    "faq.4.q": "Et si le diagnostic ne m'apprend rien ?",
    "faq.4.a": "Alors nous vous le disons, et c'est une réponse en soi : votre position tient, ne la touchez pas. Ça arrive rarement — ce qu'un fondateur trouve évident sur son métier n'apparaît presque jamais dans ce qu'il publie, et c'est cet écart que le document mesure. Dans ce cas, vous aurez économisé la refonte que vous envisagiez, ce qui coûte bien plus que 2 900 €.",
    "faq.5.q": "Qu'est-ce que je garde à la fin ?",
    "faq.5.a": "Le document entier, pour toujours. Votre diagnostic, la carte du champ, les mouvements hiérarchisés et ce qu'il faut cesser de dire.",
    "st.1.t": "Nous lisons ce que le marché lit.",
    "st.1.d": "Votre site, votre discours commercial, vos contenus, vos réseaux — et surtout ce que vos équipes racontent chacune de leur côté. La matière est déjà là ; personne ne l'a mise face à elle-même.",
    "st.1.b1": "Questionnaire d'entrée adapté à votre activité",
    "st.1.b2": "Lecture de tout ce qui vous représente",
    "st.2.t": "Nous cartographions le champ.",
    "st.2.d": "Trois à cinq concurrents directs, leur phrase exacte, et ce que chacun ose dire. C'est là qu'apparaît le terrain que personne n'occupe.",
    "st.2.b1": "Autopsie de la phrase de chaque concurrent",
    "st.2.b2": "Le mot que trois d'entre eux revendiquent",
    "st.2.b3": "Le terrain que personne n'occupe",
    "st.3.t": "Nous nommons ce que vous racontez.",
    "st.3.d": "Pas ce que vous croyez dire : ce que le marché en retient. L'écart explique pourquoi on négocie vos prix.",
    "st.3.b1": "La phrase qui porte, et celle qui vous range",
    "st.3.b2": "Le vocabulaire partagé sans le savoir",
    "st.3.b3": "Ce que votre prix dit avant vous",
    "st.4.t": "Nous donnons les mouvements.",
    "st.4.d": "Trois à cinq mouvements de repositionnement, dans l'ordre de priorité, avec ce que chacun coûte et ce qu'il débloque.",
    "st.4.b1": "Les mouvements à faire, dans l'ordre",
    "st.4.b2": "Ceux à refuser, et pourquoi",
    "st.4.b3": "Ce qu'il faut cesser de dire, et pourquoi",
    "st.5.t": "Nous vous laissons le document.",
    "st.5.d": "Vingt à trente pages, écrites à la main, à relire avec vos équipes autant de fois qu'il le faut.",
    "st.5.b1": "Un document relisable et transmissible",
    "st.5.b2": "Aucun abonnement, aucune dépendance",
    "st.title": "On lit, on compare, on tranche.",
    "st.eyebrow": "L'Architecture · la méthode S.T.R.A.W.",
    "st.hint": "Faites glisser",
    "price.b.d": "On lit votre marque comme le fait votre marché : ce qu'elle raconte aujourd'hui, ce qu'on en retient, et les mouvements qui changent ça. Un document de cinquante à soixante-dix pages, livré en trois semaines. La même Architecture que pour un lieu ou un nom propre.",
    "who.title": "Le studio qui écrit votre marque.",
    "f.required": "Champ requis",
    "price.a.d": "Elle exécute à votre place. Elle sait ce que votre marque raconte, vous non. Au bout de deux ans : environ 30 000 € dépensés, et rien qui vous appartienne.",
    "price.after": "Ensuite, si vous voulez qu'on écrive la position complète et qu'on livre les vingt pièces qui permettent à vos équipes de la tenir : l'architecture narrative, 4 500 €.",
    "who.body2": "Pas d'équipe, pas de sous-traitance, pas d'intermédiaire. Ceux qui lisent votre marque sont ceux qui écrivent le document.",
    "cta.title": "Racontez-nous votre marque.",
    "cta.lead": "Vingt minutes suffisent pour savoir si votre marque a de quoi être écrite. Nous prenons peu de maisons à la fois, et nous répondons nous-mêmes.",
    "contact.title": "Votre marque a déjà tout. Écrivons-la.",
    "f.place": "Nom de la maison",
    "f.type": "Type d'activité",
    "f.opt.r": "Marque produit",
    "f.opt.b": "Entreprise de services",
    "f.opt.c": "Studio ou agence",
    "f.opt.cs": "Autre",
    "f.message": "Où en êtes-vous aujourd'hui, et qu'aimeriez-vous que le marché comprenne de vous ?",
    "foot.tagline": "On écrit ce que votre marque raconte, et on vous donne de quoi le tenir.",
    "nav.services": "L'Architecture",
  },
  en: {
    "ex.eyebrow": "A case",
    "ex.title": "What we delivered to LOAM, and what it changed.",
    "ex.head": "Narrative architecture · Brands",
    "ex.house": "LOAM",
    "ex.lead": "LOAM, bespoke office furniture, twelve years, fourteen people. The name is changed, the deliverables are not.",
    "ex.1.n": "Piece 01",
    "case.eyebrow": "What it looks like elsewhere",
    "case.title": "Three houses that decided.",
    "case.lead": "None of them were built by us. All three did, at their scale, what this Architecture does for yours.",
    "case.1.name": "Nike",
    "case.1.refuse": "Refused to sell shoes — it sells a conviction about pushing past your limits.",
    "case.1.risk": "Talking about sport rather than product, when every competitor praised cushioning or breathability.",
    "case.1.win": "A Nike ad is recognisable before you even see the logo.",
    "case.2.name": "Coca-Cola",
    "case.2.refuse": "Refused to fragment into competing sub-brands.",
    "case.2.risk": "Resisting the temptation to diversify, segment, or modernise the name — for a century.",
    "case.2.win": "What never changes became the brand's own proof.",
    "case.3.name": "Picard",
    "case.3.refuse": "Refused to compete with greengrocers on fresh produce.",
    "case.3.risk": "Proudly selling what most chains hide or treat as a compromise.",
    "case.3.win": "Impossible to confuse with an ordinary supermarket.",
    "deliv.eyebrow": "What you receive, precisely",
    "deliv.title": "The six pieces, for your company.",
    "deliv.lead": "The same document as for any house, but nothing generic inside it.",
    "deliv.1.t": "The platform",
    "deliv.1.d": "What your company stands for, beyond the product it sells — the conviction that must hold even when the range changes.",
    "deliv.2.t": "The diagnosis",
    "deliv.2.d": "Your site, your brochure, your sales pitch gone through — the gap between what the salesperson says and what the site says.",
    "deliv.3.t": "The map",
    "deliv.3.d": "Your direct competitors dissected sentence by sentence, and the ground none of them occupy yet.",
    "deliv.4.t": "The decisions",
    "deliv.4.d": "The moves to make before any visual rebrand or campaign — in order, with what each one costs.",
    "deliv.5.t": "The playbooks",
    "deliv.5.d": "What a salesperson says in a meeting, what support answers an unhappy customer, what a new hire must understand in their first week.",
    "deliv.6.t": "The language",
    "deliv.6.d": "The vocabulary the whole company uses — from brochures to email replies — so it never sounds like the competitor next door again.",
    "ex.1.k": "The brand platform",
    "ex.1.b": "A purpose in one sentence — “furniture you do not replace” — a positioning, three values written as refusals rather than adjectives, and a tone of voice with its examples. Nine pages.",
    "ex.1.pk": "What it changed",
    "ex.1.pv": "The three values went up on a workshop wall. Two months later, the second one was used to turn down a €40,000 chipboard order — the first time the refusal could be justified in front of the team.",
    "ex.2.n": "Piece 03",
    "ex.2.k": "The map of the field",
    "ex.2.b": "Five competitors, their homepage line quoted word for word, what each one claims, and the record of shared words. The finding: “bespoke” in three of them, “artisanal” in three as well, lead time claimed by none.",
    "ex.2.pk": "What it changed",
    "ex.2.pv": "LOAM stopped using “bespoke”, which appeared eleven times on their site. It was replaced by the lead time — the only ground the panel left open, and the only one they could hold: they are the only ones drying in-house.",
    "ex.3.n": "Piece 04",
    "ex.3.k": "The decisions",
    "ex.3.b": "Four ordered moves. The first: replace the homepage line with the refusal, with the exact wording to use. Each one measured — what it costs, what it loses, in which order to do it.",
    "ex.3.pk": "What it changed",
    "ex.3.pv": "Move 1 was costed at an estimated 25% loss of inbound enquiries. They took it. Enquiries dropped; the close rate rose, because the ones left were no longer calling to compare a lead time.",
    "ex.4.n": "Piece 05",
    "ex.4.k": "The playbooks",
    "ex.4.b": "Five playbooks — sales, content, social, support, hiring. The sales one holds the three real objections found in their lost quotes, and the answer to each. The hiring one names the disqualifying trait.",
    "ex.4.pk": "What it changed",
    "ex.4.pv": "The salesperson who joined in March was operational without training: he read the playbook and used its wording. His first quote did not need proofreading — a first in twelve years.",
    "ex.foot": "Six pieces delivered. Four shown here.",
    "tour.out": "You already have everything you need. What is missing is an identity to make it visible.",
    "hero.kicker": "Narrative architecture · Brands & companies",
    "mq.1": "Brands",
    "mq.2": "Companies",
    "mq.3": "Studios",
    "mq.4": "Practices",
    "mq.5": "Publishers",
    "mq.6": "Workshops",
    "hero.tag": "A competitor half as good<br/><b>signs the contracts that were yours.</b>",
    "man.eyebrow": "The finding",
    "man.body": "<b>A competitor half as good as you signs the contracts that should have been yours.</b> They do not work better. They do not deliver better. They tell it better — and in a market where nobody can judge quality before buying, that is the only thing that decides.",
    "man.body2": "Your product holds, your customers come back. But you get asked for a comparative quote before anyone has listened to you, because nothing you say says what you refuse. <em>Your story has never been written.</em>",
    "focus.eyebrow": "The difference",
    "focus.title": "Communicating, or holding a position.",
    "focus.lead": "The same brand, two realities. Take the handle and pull.",
    "focus.bad.tag": "A brand that communicates",
    "focus.bad.big": "Every statement starts from nothing. Nobody knows what you claim, or what you refuse.",
    "focus.good.tag": "A brand that holds a position",
    "focus.good.big": "The position is written. The whole team knows what you claim and what you refuse.",
    "faq.title": "What founders ask us.",
    "faq.1.q": "Why not a monthly agency?",
    "faq.1.a": "Because after two years you will have spent around 30,000 € and kept nothing. Here you pay 2 900 € once, and the document is yours.",
    "faq.2.q": "What can I do with it on my own?",
    "faq.2.a": "Everything. The document names the moves in order, with their cost. You can apply them without us — that is the point.",
    "faq.3.q": "How much of my time does it take?",
    "faq.3.a": "About an hour. An entry questionnaire, then we work without taking your time. The document arrives within three weeks.",
    "faq.4.q": "What if the diagnosis teaches me nothing?",
    "faq.4.a": "Then we tell you so, and that is an answer in itself: your position holds, leave it alone. It happens rarely — what a founder finds obvious about their work almost never shows up in what they publish, and that gap is what the document measures. In that case you will have saved the rebuild you were considering, which costs far more than 2 900 €.",
    "faq.5.q": "What do I keep at the end?",
    "faq.5.a": "The whole document, forever. Your diagnosis, the map of the field, the ranked moves and what to stop saying.",
    "st.1.t": "We read what the market reads.",
    "st.1.d": "Your site, your sales pitch, your content — and what each team says on its own.",
    "st.1.b1": "An entry questionnaire matched to your business",
    "st.1.b2": "A reading of everything that represents you",
    "st.2.t": "We map the field.",
    "st.2.d": "Three to five direct competitors, their exact sentence, and the argument each one dares to carry.",
    "st.2.b1": "An autopsy of each competitor's sentence",
    "st.2.b2": "The word three of them claim",
    "st.2.b3": "The ground nobody occupies",
    "st.3.t": "We name what you actually say.",
    "st.3.d": "Not what you think you say: what the market keeps. The gap explains why your prices get negotiated.",
    "st.3.b1": "The sentence that carries, and the one that files you",
    "st.3.b2": "The vocabulary shared without knowing",
    "st.3.b3": "What your price says before you do",
    "st.4.t": "We hand over the moves.",
    "st.4.d": "Three to five repositioning moves, ranked, with what each one costs and unlocks.",
    "st.4.b1": "The moves to make, in order",
    "st.4.b2": "The ones to refuse, and why",
    "st.4.b3": "What to stop saying",
    "st.5.t": "We leave you the document.",
    "st.5.d": "Twenty to thirty pages, written by hand, to go through with your teams as often as needed.",
    "st.5.b1": "A document you can re-read and pass on",
    "st.5.b2": "No subscription, no dependency",
    "st.title": "We read, we compare, we settle.",
    "st.eyebrow": "The Architecture · the S.T.R.A.W. method",
    "st.hint": "Drag across",
    "price.b.d": "We read your brand the way your market does: what it says today, what people keep of it, and the moves that change that. A fifty to seventy page document, delivered in three weeks. The same Architecture as for a venue or a name.",
    "who.title": "The studio that writes your brand.",
    "f.required": "Required field",
    "price.a.d": "It executes in your place. It knows what your brand says, you do not. After two years: roughly 30,000 € spent, and nothing that belongs to you.",
    "price.after": "Then, if you want the full position written and the twenty pieces that let your teams hold it: the narrative architecture, 4,500 €.",
    "who.body2": "No team, no subcontracting, no middleman. The people who read your brand are the people who write the document.",
    "cta.title": "Tell us about your brand.",
    "cta.lead": "Twenty minutes is enough to know whether your brand has something worth writing. We take on few houses at a time, and we answer ourselves.",
    "contact.title": "Your brand already has everything. Let's write it.",
    "f.place": "Name of the house",
    "f.type": "Type of business",
    "f.opt.r": "Product brand",
    "f.opt.b": "Service company",
    "f.opt.c": "Studio or agency",
    "f.opt.cs": "Other",
    "f.message": "Where are you today, and what would you like the market to understand about you?",
    "foot.tagline": "We write what your brand says, and hand you what you need to hold it.",
    "nav.services": "The Architecture",
  },
}

export default function BrandTerrainPage() {
  return <TerrainPage copy={COPY} />
}
