import type { Metadata } from "next"
import { TerrainPage, type TerrainCopy } from "@/components/terrain/terrain-page"

/**
 * BRAND — le terrain marques & entreprises.
 *
 * Même page que THE ROOM, au caractère près : même HTML, même CSS, même
 * JavaScript, donc le canvas bokeh, la tournée épinglée, le comparateur et
 * l'accordéon sont identiques. Seul le texte change, par surcharge du
 * dictionnaire.
 *
 * Les clés non surchargées héritent du texte de THE ROOM : ce sont celles
 * qui parlent du studio, du prix ou de la méthode, et qui sont vraies quel
 * que soit le terrain — c'est exactement ce que l'unification affirme.
 */

export const metadata: Metadata = {
  title: "BRAND — L'architecture narrative pour les marques et les entreprises",
  description:
    "On vous compare au prix parce que rien ne dit qui vous êtes. L'architecture narrative lit ce que votre marque raconte aujourd'hui et donne les mouvements qui la sortent du rayon.",
}

const COPY: TerrainCopy = {
  slug: "marques-entreprises",
  wordmark: "BRAND",
  fr: {
    "case.normLabel": "Ce que fait le secteur",
    "case.refuseLabel": "Ce qu'elle a fait",
    "case.resultLabel": "Ce que ça a donné",
    "case.eyebrow": "Ce que ça donne, ailleurs",
    "case.title": "Trois maisons qui ont tranché.",
    "case.lead": "Aucune n'a été construite par nous. Toutes les trois ont fait, à leur échelle, ce que cette Architecture fait à la vôtre.",
    "case.1.name": "Nike",
    "case.1.norm": "Dans les années 1980, l'argument publicitaire du sport était technique — amorti, respirabilité, poids de la semelle.",
    "case.1.refuse": "« Just Do It » ne décrit aucune caractéristique produit : c'est une conviction sur ce que ça fait de dépasser sa propre limite, adressée à quiconque bouge, pas seulement aux athlètes. Le pari était risqué — abandonner l'argument rationnel que la concurrence maîtrisait, pour un territoire qu'aucune fiche technique ne peut prouver.",
    "case.1.body": "Près de quarante ans plus tard, la marque n'a jamais eu besoin de changer ce message pour rester pertinente, parce qu'il ne parlait jamais du produit lui-même.",
    "case.2.name": "Coca-Cola",
    "case.2.norm": "Quand un concurrent lance une nouvelle saveur ou une charte graphique rafraîchie, la tentation de suivre est immédiate — rester visible, prouver qu'on avance.",
    "case.2.refuse": "Coca-Cola a résisté à cette pression pendant un siècle entier, gardant le même rouge, la même typographie, la même promesse de bonheur simple. Le seul écart notable, la reformulation de 1985, a été un échec si retentissant qu'il a renforcé la leçon.",
    "case.2.body": "Ce qui ne change pas devient la preuve elle-même : la marque n'a plus besoin de convaincre qu'elle est fiable, elle l'est visiblement, depuis toujours, sous les yeux de tous.",
    "case.3.name": "Picard",
    "case.3.norm": "Le surgelé porte, dans l'imaginaire français, une connotation de dépannage — ce qu'on achète quand on n'a pas le temps de faire mieux. La plupart des enseignes du secteur jouent la discrétion, misant sur le prix plutôt que sur l'identité.",
    "case.3.refuse": "Picard a fait l'inverse : revendiquer le surgelé comme une expertise, avec des vitrines soignées et un discours qui ne s'excuse jamais. Le risque était réel — se distinguer d'un secteur entier qui préfère se fondre dans le décor du supermarché classique.",
    "case.3.body": "Le résultat, c'est une enseigne qu'on ne confond avec aucune autre, alors que le produit qu'elle vend est, sur le papier, une commodité.",
    "tour.out": "Vous avez déjà tout ce qu'il faut. Ce qui manque, c'est une identité pour le rendre visible.",
    "hero.kicker": "Architecture narrative · Marques & entreprises",
    "mq.1": "Marques",
    "mq.2": "Entreprises",
    "mq.3": "Studios",
    "mq.4": "Cabinets",
    "mq.5": "Éditeurs",
    "mq.6": "Ateliers",
    "hero.tag": "Un concurrent deux fois moins bon<br/><b>signe les contrats qui étaient les vôtres.</b>",
    "man.eyebrow": "Le constat",
    "man.body": "<b>Un concurrent deux fois moins bon que vous signe les contrats qui auraient dû être les vôtres.</b> Il ne travaille pas mieux. Il ne livre pas mieux. Il se raconte mieux — et sur un marché où personne ne peut juger la qualité avant d'acheter, c'est le seul critère qui tranche.",
    "man.body2": "Votre produit tient, vos clients reviennent. Mais on vous demande un devis comparatif avant même de vous avoir écouté, parce que rien dans ce que vous dites ne dit ce que vous refusez. <em>Votre récit n'a jamais été écrit.</em>",
    "focus.eyebrow": "La différence",
    "focus.title": "Communiquer, ou tenir une position.",
    "focus.lead": "La même marque, deux réalités. Prenez la poignée et tirez : à gauche on communique sans savoir quoi défendre, à droite la position est écrite et toute l'équipe la tient.",
    "focus.bad.tag": "Une marque qui communique",
    "focus.bad.big": "Chaque prise de parole repart de zéro. Personne ne sait ce qu'on revendique, ni ce qu'on refuse.",
    "focus.good.tag": "Une marque qui tient une position",
    "focus.good.big": "La position est écrite. N'importe qui dans l'équipe sait ce qu'on revendique et ce qu'on refuse. Tout se ressemble, sans se répéter.",
    "faq.title": "Ce que les dirigeants nous demandent.",
    "st.1.t": "Nous lisons ce que le marché lit.",
    "st.1.d": "Votre site, votre discours commercial, vos contenus, vos réseaux — et surtout ce que vos équipes racontent chacune de leur côté. La matière est déjà là ; personne ne l'a mise face à elle-même.",
    "st.1.b1": "Questionnaire d'entrée adapté à votre activité",
    "st.1.b2": "Lecture de tout ce qui vous représente",
    "st.2.t": "Nous cartographions le champ.",
    "st.2.d": "Trois à cinq concurrents directs, leur phrase exacte, et ce que chacun ose dire. C'est là qu'apparaît le terrain que personne n'occupe.",
    "st.2.b1": "Autopsie de la phrase de chaque concurrent",
    "st.2.b2": "Le mot que trois d'entre eux revendiquent",
    "st.2.b3": "Le terrain que personne n'occupe",
    "st.3.t": "Nous nommons ce que vous racontez.",
    "st.3.d": "Pas ce que vous croyez dire : ce que le marché en retient. L'écart explique pourquoi on négocie vos prix.",
    "st.3.b1": "La phrase qui porte, et celle qui vous range",
    "st.3.b2": "Le vocabulaire partagé sans le savoir",
    "st.3.b3": "Ce que votre prix dit avant vous",
    "st.4.t": "Nous donnons les mouvements.",
    "st.4.d": "Trois à cinq mouvements de repositionnement, dans l'ordre de priorité, avec ce que chacun coûte et ce qu'il débloque.",
    "st.4.b1": "Les mouvements à faire, dans l'ordre",
    "st.4.b2": "Ceux à refuser, et pourquoi",
    "st.4.b3": "Ce qu'il faut cesser de dire, et pourquoi",
    "st.5.t": "Nous vous laissons le document.",
    "st.5.d": "Vingt à trente pages, écrites à la main, à relire avec vos équipes autant de fois qu'il le faut.",
    "st.5.b1": "Un document relisable et transmissible",
    "st.5.b2": "Aucun abonnement, aucune dépendance",
    "st.title": "On lit, on compare, on tranche.",
    "st.eyebrow": "L'Architecture · la méthode S.T.R.A.W.",
    "st.hint": "Faites glisser",
    "who.title": "Le studio qui écrit votre marque.",
    "f.required": "Champ requis",
    "who.body2": "Pas d'équipe, pas de sous-traitance, pas d'intermédiaire. Ceux qui lisent votre marque sont ceux qui écrivent le document.",
    "cta.title": "Racontez-nous votre marque.",
    "contact.title": "Votre marque a déjà tout. Écrivons-la.",
    "f.place": "Nom de la maison",
    "f.type": "Type d'activité",
    "f.opt.r": "Marque produit",
    "f.opt.b": "Entreprise de services",
    "f.opt.c": "Studio ou agence",
    "f.opt.cs": "Autre",
    "f.message": "Où en êtes-vous aujourd'hui, et qu'aimeriez-vous que le marché comprenne de vous ?",
    "foot.tagline": "On écrit ce que votre marque raconte, et on vous donne de quoi le tenir.",
    "nav.services": "L'Architecture",
    "for.yes.1": "Vous dirigez une maison de une à vingt personnes, en activité depuis trois à dix ans.",
    "for.no.1": "Vous cherchez quelqu'un pour produire du contenu ou tenir vos réseaux.",
    "for.yes.2": "Votre travail est meilleur que celui du marché, et on vous met pourtant en concurrence avec des noms plus grossiers.",
    "for.no.2": "Vous voulez refaire un logo ou une identité visuelle.",
    "for.yes.3": "Vous voulez un document que vos équipes appliquent sans vous : position, langage, playbooks.",
    "for.no.3": "Vous n'avez encore ni clients ni travail publié à lire.",
    "faq.1.q": "Pourquoi pas une agence au mois ?",
    "faq.1.a": "Parce qu'au bout de deux ans vous aurez payé environ 30 000 € sans rien garder. Ici vous payez 2 900 € une fois, et le document vous appartient.",
    "faq.2.q": "Mes commerciaux vont-ils vraiment s'en servir ?",
    "faq.2.a": "C'est ce que le playbook vente est fait pour. Il contient vos trois objections réelles avec la réponse à chacune, la formulation exacte quand on demande un devis comparatif, et ce qu'on ne concède jamais. Un commercial qui arrive le lundi peut l'utiliser à son premier rendez-vous : c'est le test qu'on s'applique.",
    "faq.3.q": "Je vends aussi des produits, ou j'ai plusieurs activités ?",
    "faq.3.a": "C'est le cas le plus courant. La méthode, le prix et le délai ne changent pas : l'Architecture porte sur la maison, et le lexique comme les playbooks valent pour tout ce que vous vendez. Dites-nous dans le questionnaire ce qui porte le plus de chiffre : c'est là que le diagnostic se concentre.",
    "faq.7.q": "Et si le diagnostic ne m'apprend rien ?",
    "faq.7.a": "Alors nous vous le disons, et c'est une réponse en soi : votre position tient, ne la touchez pas. Ça arrive rarement : ce qu'un fondateur trouve évident sur son métier n'apparaît presque jamais dans ce qu'il publie, et c'est cet écart que le document mesure. Dans ce cas, vous aurez économisé la refonte que vous envisagiez, ce qui coûte bien plus que 2 900 €.",
    "faq.8.q": "Qu'est-ce que je garde à la fin ?",
    "faq.8.a": "Tout, sans abonnement. Le document est à vous, avec un droit d'usage commercial illimité et perpétuel : votre diagnostic, la carte du champ, les mouvements hiérarchisés, ce qu'il faut cesser de dire. Vos équipes l'appliquent sans nous.",
    "cta.lead": "2 900 €, livré en trois semaines, ou remboursé. Un document écrit pour votre marque, à vous pour toujours.",
  },
  en: {
    "case.normLabel": "What the industry does",
    "case.refuseLabel": "What it did",
    "case.resultLabel": "What it earned",
    "case.eyebrow": "What it looks like elsewhere",
    "case.title": "Three houses that decided.",
    "case.lead": "None of them were built by us. All three did, at their scale, what this Architecture does for yours.",
    "case.1.name": "Nike",
    "case.1.norm": "In the 1980s, sport advertising argued on specs — cushioning, breathability, sole weight.",
    "case.1.refuse": "\"Just Do It\" describes no product feature at all: it is a conviction about what it feels like to push past your own limit, aimed at anyone who moves, not only elite athletes. The bet was risky — giving up the rational argument competitors owned, for ground no spec sheet can prove.",
    "case.1.body": "Nearly forty years later, the brand has never needed to change that message to stay relevant, because it was never about the product in the first place.",
    "case.2.name": "Coca-Cola",
    "case.2.norm": "When a competitor launches a new flavour or a refreshed look, the pull to follow is immediate — stay visible, prove you're moving forward.",
    "case.2.refuse": "Coca-Cola resisted that pressure for an entire century, keeping the same red, the same typography, the same promise of simple happiness. The one notable exception, the 1985 reformulation, failed so loudly it reinforced the lesson.",
    "case.2.body": "What never changes becomes the proof itself: the brand no longer needs to argue it is trustworthy, it visibly is, and always has been, in plain sight.",
    "case.3.name": "Picard",
    "case.3.norm": "In the French imagination, frozen food carries a fallback connotation — what you buy when there's no time to do better. Most chains in the category play it down, competing on price rather than identity.",
    "case.3.refuse": "Picard did the opposite: claiming frozen food as an expertise, with carefully designed storefronts and messaging that never apologises. The risk was real — standing out from an entire category that prefers to blend into ordinary supermarket shelving.",
    "case.3.body": "The result is a chain impossible to confuse with any other, even though what it sells is, on paper, a commodity.",
    "tour.out": "You already have everything you need. What is missing is an identity to make it visible.",
    "hero.kicker": "Narrative architecture · Brands & companies",
    "mq.1": "Brands",
    "mq.2": "Companies",
    "mq.3": "Studios",
    "mq.4": "Practices",
    "mq.5": "Publishers",
    "mq.6": "Workshops",
    "hero.tag": "A competitor half as good<br/><b>signs the contracts that were yours.</b>",
    "man.eyebrow": "The finding",
    "man.body": "<b>A competitor half as good as you signs the contracts that should have been yours.</b> They do not work better. They do not deliver better. They tell it better — and in a market where nobody can judge quality before buying, that is the only thing that decides.",
    "man.body2": "Your product holds, your customers come back. But you get asked for a comparative quote before anyone has listened to you, because nothing you say says what you refuse. <em>Your story has never been written.</em>",
    "focus.eyebrow": "The difference",
    "focus.title": "Communicating, or holding a position.",
    "focus.lead": "The same brand, two realities. Take the handle and pull.",
    "focus.bad.tag": "A brand that communicates",
    "focus.bad.big": "Every statement starts from nothing. Nobody knows what you claim, or what you refuse.",
    "focus.good.tag": "A brand that holds a position",
    "focus.good.big": "The position is written. The whole team knows what you claim and what you refuse.",
    "faq.title": "What founders ask us.",
    "st.1.t": "We read what the market reads.",
    "st.1.d": "Your site, your sales pitch, your content — and what each team says on its own.",
    "st.1.b1": "An entry questionnaire matched to your business",
    "st.1.b2": "A reading of everything that represents you",
    "st.2.t": "We map the field.",
    "st.2.d": "Three to five direct competitors, their exact sentence, and the argument each one dares to carry.",
    "st.2.b1": "An autopsy of each competitor's sentence",
    "st.2.b2": "The word three of them claim",
    "st.2.b3": "The ground nobody occupies",
    "st.3.t": "We name what you actually say.",
    "st.3.d": "Not what you think you say: what the market keeps. The gap explains why your prices get negotiated.",
    "st.3.b1": "The sentence that carries, and the one that files you",
    "st.3.b2": "The vocabulary shared without knowing",
    "st.3.b3": "What your price says before you do",
    "st.4.t": "We hand over the moves.",
    "st.4.d": "Three to five repositioning moves, ranked, with what each one costs and unlocks.",
    "st.4.b1": "The moves to make, in order",
    "st.4.b2": "The ones to refuse, and why",
    "st.4.b3": "What to stop saying",
    "st.5.t": "We leave you the document.",
    "st.5.d": "Twenty to thirty pages, written by hand, to go through with your teams as often as needed.",
    "st.5.b1": "A document you can re-read and pass on",
    "st.5.b2": "No subscription, no dependency",
    "st.title": "We read, we compare, we settle.",
    "st.eyebrow": "The Architecture · the S.T.R.A.W. method",
    "st.hint": "Drag across",
    "who.title": "The studio that writes your brand.",
    "f.required": "Required field",
    "who.body2": "No team, no subcontracting, no middleman. The people who read your brand are the people who write the document.",
    "cta.title": "Tell us about your brand.",
    "contact.title": "Your brand already has everything. Let's write it.",
    "f.place": "Name of the house",
    "f.type": "Type of business",
    "f.opt.r": "Product brand",
    "f.opt.b": "Service company",
    "f.opt.c": "Studio or agency",
    "f.opt.cs": "Other",
    "f.message": "Where are you today, and what would you like the market to understand about you?",
    "foot.tagline": "We write what your brand says, and hand you what you need to hold it.",
    "nav.services": "The Architecture",
    "for.yes.1": "You run a house of one to twenty people, three to ten years in.",
    "for.no.1": "You are looking for someone to produce content or run your channels.",
    "for.yes.2": "Your work is better than the market's, yet you are shortlisted next to cruder names.",
    "for.no.2": "You want a new logo or visual identity.",
    "for.yes.3": "You want a document your teams apply without you: position, language, playbooks.",
    "for.no.3": "You have no clients yet and no published work to read.",
    "faq.1.q": "Why not a monthly agency?",
    "faq.1.a": "Because after two years you will have spent around €30,000 and kept nothing. Here you pay €2,900 once, and the document is yours.",
    "faq.2.q": "Will my sales team really use it?",
    "faq.2.a": "That is what the sales playbook is for. It holds your three real objections with an answer to each, the exact wording when someone asks for a comparative quote, and what is never conceded. A salesperson who starts on Monday can use it in their first meeting: that is the test we apply to it.",
    "faq.3.q": "I also sell products, or I have several activities.",
    "faq.3.a": "This is the most common case. The method, the price and the deadline do not change: the Architecture covers the house, and the lexicon and playbooks apply to everything you sell. Tell us in the questionnaire what carries the most revenue: that is where the diagnosis concentrates.",
    "faq.7.q": "What if the diagnosis teaches me nothing?",
    "faq.7.a": "Then we tell you so, and that is an answer in itself: your position holds, leave it alone. It happens rarely: what a founder finds obvious about their work almost never shows up in what they publish, and that gap is what the document measures. In that case you will have saved the rebuild you were considering, which costs far more than €2,900.",
    "faq.8.q": "What do I keep at the end?",
    "faq.8.a": "Everything, with no subscription. The document is yours, with unlimited and perpetual commercial use: your diagnosis, the map of the field, the ranked moves, what to stop saying. Your teams apply it without us.",
    "cta.lead": "€2,900, delivered in three weeks, or refunded. A document written for your brand, yours for good.",
  },
}

export default function BrandTerrainPage() {
  return <TerrainPage copy={COPY} />
}
