import type { Metadata } from "next"
import { TerrainPage, type TerrainCopy } from "@/components/terrain/terrain-page"

/**
 * THE NAME — le terrain artistes & fondateurs.
 *
 * Même page que THE ROOM et BRAND : même HTML, même CSS, même JavaScript.
 * Seul le dictionnaire change.
 *
 * Remplace l'ancienne page /artistes, qui portait la mise en page de
 * MOMENTUM — une charte de plus à maintenir, pour un terrain qui n'avait
 * aucune raison d'avoir la sienne.
 */

export const metadata: Metadata = {
  title: "THE NAME — L'audit narratif pour les artistes et les fondateurs",
  description:
    "Vos sorties ne s'additionnent pas. L'audit narratif dit ce que votre nom raconte aujourd'hui et donne les mouvements qui font tenir le fil.",
}

const COPY: TerrainCopy = {
  slug: "the-name",
  wordmark: "THE NAME",
  fr: {
    "mq.1": "Musiciens",
    "mq.2": "Réalisateurs",
    "mq.3": "Fondateurs",
    "mq.4": "Auteurs",
    "mq.5": "Photographes",
    "mq.6": "Créateurs",
    "hero.tag": "On aime ce que vous faites sans savoir dire ce que vous êtes.",
    "man.eyebrow": "Le constat",
    "man.body": "Votre travail est bon. Les retours sont bons. <b>Et pourtant</b>, chaque sortie repart de zéro — parce que rien ne relie la précédente à la suivante dans la tête de ceux qui vous suivent. Pendant ce temps, quelqu'un de moins doué construit une audience qui l'attend. Il ne produit pas mieux. <b>Il se raconte mieux.</b>",
    "man.body2": "Vous n'avez pas un problème de production. Vous avez un problème de fil. Un nom porte déjà un récit — une origine, une obsession, un refus, une manière. <b>Le vôtre n'a jamais été écrit.</b>",
    "focus.eyebrow": "La différence",
    "focus.title": "Publier, ou se raconter.",
    "focus.lead": "Le même nom, deux réalités. Prenez la poignée et tirez : à gauche on publie sans fil conducteur, à droite le récit est écrit et chaque sortie s'appuie sur la précédente.",
    "focus.bad.tag": "Un nom qui publie",
    "focus.bad.big": "Chaque sortie repart de zéro. Le public découvre à chaque fois, au lieu d'attendre.",
    "focus.good.tag": "Un nom qui se raconte",
    "focus.good.big": "Le fil est écrit. Chaque sortie confirme la précédente au lieu de repartir de zéro. Tout se ressemble, sans se répéter.",
    "faq.title": "Ce que les artistes nous demandent.",
    "faq.1.q": "Pourquoi pas un attaché de presse ?",
    "faq.1.a": "Un attaché de presse diffuse un récit. Il ne l'écrit pas. L'audit vous donne ce qu'il diffusera — et il travaillera mieux avec.",
    "faq.2.q": "Je débute, est-ce trop tôt ?",
    "faq.2.a": "S'il existe au moins deux ou trois sorties à lire, non. S'il n'y a rien encore, oui : il n'y a pas de matière à auditer, et nous vous le dirons.",
    "faq.3.q": "Combien de temps ça prend, de mon côté ?",
    "faq.3.a": "Quelques heures en tout. Un questionnaire d'entrée, un échange avec vous, et la remise du document. Le reste du travail se fait sans vous mobiliser.",
    "faq.4.q": "Et si ça formate mon travail ?",
    "faq.4.a": "C'est prévu. Le document est écrit pour être appliqué seul : ce que vous revendiquez, ce que vous refusez, avec quels mots. Aucune interprétation n'est laissée au lecteur.",
    "faq.5.q": "Qu'est-ce que je garde à la fin ?",
    "faq.5.a": "Le document entier, pour toujours. Votre fil nommé, la carte de votre zone, les mouvements hiérarchisés et ce qu'il faut cesser de dire.",
    "st.1.t": "Nous lisons tout ce que vous avez sorti.",
    "st.1.d": "Vos projets, vos textes, vos visuels, vos interviews — et ce que la presse retient quand elle vous résume en une phrase. Le fil est déjà là ; personne ne l'a nommé.",
    "st.1.b1": "Questionnaire d'entrée adapté à votre pratique",
    "st.1.b2": "Lecture de vos sorties et de ce qu'on en dit",
    "st.2.t": "Nous cartographions votre zone.",
    "st.2.d": "Trois à cinq artistes à qui on vous compare, ou dont vous partagez le public. Pas vos influences : ceux qui occupent le terrain que vous visez.",
    "st.2.b1": "Autopsie de la bio de chacun",
    "st.2.b2": "Ce que vous partagez sans le vouloir",
    "st.2.b3": "La place qui reste libre",
    "st.3.t": "Nous nommons votre fil.",
    "st.3.d": "Pas ce que vous voulez qu'il raconte : ce que le public en retient. L'écart explique pourquoi vos sorties ne s'additionnent pas.",
    "st.3.b1": "Le fil réel, sous vos projets",
    "st.3.b2": "Ce qui vous rend confondable",
    "st.3.b3": "Ce que votre bio dit avant vous",
    "st.4.t": "Nous donnons les mouvements.",
    "st.4.d": "Trois à cinq mouvements, dans l'ordre de priorité, avec ce que chacun coûte et ce qu'il débloque.",
    "st.4.b1": "Les mouvements à faire, dans l'ordre",
    "st.4.b2": "Ceux à refuser, et pourquoi",
    "st.4.b3": "Ce qu'il faut cesser de dire, et pourquoi",
    "st.5.t": "Nous vous laissons le document.",
    "st.5.d": "Vingt à trente pages, écrites à la main, utilisables seul comme avec votre label ou votre agent.",
    "st.5.b1": "Un document relisable et transmissible",
    "st.5.b2": "Aucun abonnement, aucune dépendance",
    "st.title": "Sept à quatorze jours, cinq blocs.",
    "st.eyebrow": "L'audit",
    "st.hint": "Faites glisser",
    "price.b.d": "On lit votre nom comme le fait votre public : ce qu'il raconte aujourd'hui, ce qu'on en retient, et les mouvements qui changent ça. Un document de vingt à trente pages, livré en sept jours. Le même audit que pour une marque ou un lieu.",
    "who.title": "Le studio qui écrit votre nom.",
    "f.required": "Champ requis",
    "stat.3.l": "Seul document, pour toute votre carrière",
    "price.a.d": "Elle exécute à votre place. Elle sait ce que votre nom raconte, vous non. Au bout de deux ans : environ 30 000 € dépensés, et rien qui vous appartienne.",
    "price.after": "Ensuite, si vous voulez qu'on écrive le récit complet et qu'on livre les vingt pièces qui le tiennent dans la durée : l'architecture narrative, 4 500 €.",
    "who.body2": "Pas d'équipe, pas de sous-traitance, pas d'intermédiaire. Ceux qui lisent votre travail sont ceux qui écrivent le document.",
    "cta.title": "Racontez-nous votre travail.",
    "cta.lead": "Vingt minutes suffisent pour savoir si votre nom a de quoi être écrit. Nous prenons peu de projets à la fois, et nous répondons nous-mêmes.",
    "contact.title": "Votre travail a déjà tout. Écrivons-le.",
    "f.place": "Nom d'artiste ou nom propre",
    "f.type": "Pratique",
    "f.opt.r": "Musique",
    "f.opt.b": "Image et cinéma",
    "f.opt.c": "Écriture",
    "f.opt.cs": "Autre",
    "f.message": "Où en êtes-vous aujourd'hui, et qu'aimeriez-vous que le public comprenne de vous ?",
    "foot.tagline": "On écrit ce que votre nom raconte, et on vous donne de quoi le tenir.",
    "nav.services": "L'audit",
  },
  en: {
    "mq.1": "Musicians",
    "mq.3": "Founders",
    "mq.4": "Writers",
    "man.body": "Your work is good. The feedback is good. <b>And yet</b>, every release starts from zero — because nothing links the last one to the next in the minds of the people who follow you. Meanwhile someone less gifted is building an audience that waits for them. They do not make better work. <b>They tell it better.</b>",
    "man.body2": "You do not have a production problem. You have a thread problem. A name already carries a story — an origin, an obsession, a refusal, a way of doing things. <b>Yours has never been written.</b>",
    "st.1.d": "Your projects, your writing, your visuals, your interviews — and what the press keeps when it sums you up in one line. The thread is already there; nobody has named it.",
    "st.1.b1": "An entry questionnaire matched to your practice",
    "st.2.d": "Three to five artists you get compared to, or whose audience you share. Not your influences: the ones holding the ground you aim at.",
    "st.2.b1": "An autopsy of each of their bios",
    "st.4.d": "Three to five moves, in priority order, with what each one costs and what it unlocks.",
    "st.4.b3": "What to stop saying, and why",
    "price.b.d": "We read your name the way your audience does: what it says today, what people keep of it, and the moves that change that. A twenty to thirty page document, delivered in seven days. The same audit as for a brand or a venue.",
    "who.title": "The studio that writes your name.",
    "f.required": "Required field",
    "focus.lead": "The same name, two realities. Take the handle and pull: on the left, posting with no thread; on the right, the story is written and each release builds on the last.",
    "focus.bad.tag": "A name that posts",
    "focus.good.tag": "A name that tells its story",
    "focus.good.big": "The thread is written. Each release confirms the last instead of starting from zero. Everything belongs together, without repeating itself.",
    "stat.3.l": "Single document, for a whole career",
    "price.a.d": "It executes in your place. It knows what your name says, you do not. After two years: roughly 30,000 € spent, and nothing that belongs to you.",
    "price.after": "Then, if you want the full story written and the twenty pieces that hold it over time: the narrative architecture, 4,500 €.",
    "who.body2": "No team, no subcontracting, no middleman. The people who read your work are the people who write the document.",
    "faq.3.a": "A few hours in total. An entry questionnaire, a conversation with you, and the delivery. The rest of the work happens without taking your time.",
    "faq.4.a": "That is accounted for. The document is written to be applied alone: what you claim, what you refuse, in which words. Nothing is left to interpretation.",
    "cta.title": "Tell us about your work.",
    "cta.lead": "Twenty minutes is enough to know whether your name has something worth writing. We take on few projects at a time, and we answer ourselves.",
    "contact.title": "Your work already has everything. Let's write it.",
    "f.place": "Artist name or own name",
    "f.type": "Practice",
    "f.opt.r": "Music",
    "f.opt.b": "Image and film",
    "f.opt.c": "Writing",
    "f.opt.cs": "Other",
    "f.message": "Where are you today, and what would you like the audience to understand about you?",
    "foot.tagline": "We write what your name says, and hand you what you need to hold it.",
    "nav.services": "The audit",
    "hero.tag": "People like what you do without being able to say what you are.",
  },
}

export default function NameTerrainPage() {
  return <TerrainPage copy={COPY} />
}
