import type { Metadata } from "next"
import { TerrainPage, type TerrainCopy } from "@/components/terrain/terrain-page"

/**
 * THE NAME — le terrain artistes & fondateurs.
 *
 * Même page que THE ROOM et BRAND : même HTML, même CSS, même JavaScript.
 * Seul le dictionnaire change.
 *
 * Remplace l'ancienne page /artistes, qui portait la mise en page de
 * MOMENTUM — une charte de plus à maintenir, pour un terrain qui n'avait
 * aucune raison d'avoir la sienne.
 */

export const metadata: Metadata = {
  title: "THE NAME — L'architecture narrative pour les artistes et les fondateurs",
  description:
    "Vos sorties ne s'additionnent pas. L'architecture narrative dit ce que votre nom raconte aujourd'hui et donne les mouvements qui font tenir le fil.",
}

const COPY: TerrainCopy = {
  slug: "the-name",
  wordmark: "THE NAME",
  fr: {
    "case.normLabel": "Ce que fait le secteur",
    "case.refuseLabel": "Ce qu'elle a fait",
    "case.resultLabel": "Ce que ça a donné",
    "case.eyebrow": "Ce que ça donne, ailleurs",
    "case.title": "Trois noms qui ont tranché.",
    "case.lead": "Aucun n'a été construit par nous. Tous les trois ont fait, à leur échelle, ce que cette Architecture fait pour vous.",
    "case.1.name": "Travis Scott",
    "case.1.norm": "La plupart des artistes qui réussissent dans un domaine y restent, pour ne pas diluer leur reconnaissance.",
    "case.1.refuse": "Travis Scott a construit le même univers visuel et sonore — chaotique, saturé, presque cinématographique — à travers ses albums, ses collections de vêtements et une collaboration dans un jeu vidéo joué par des centaines de millions de personnes. Chaque nouveau terrain était un risque : perdre en cohérence, ou pire, perdre en crédibilité dans un domaine qui n'est pas le sien.",
    "case.1.body": "C'est l'inverse qui s'est produit, parce que l'univers, pas le médium, est devenu la signature. On reconnaît un projet Travis Scott avant même d'avoir entendu un son.",
    "case.2.name": "Beyoncé",
    "case.2.norm": "L'industrie musicale repose sur un rituel bien rodé — annonce, singles, interviews, tournée de promotion pendant des mois.",
    "case.2.refuse": "Beyoncé a choisi, à plusieurs reprises, de sortir un album entier sans prévenir personne, sans single précédent, sans interview. Le risque était direct : aucun battage médiatique construit à l'avance pour porter les ventes.",
    "case.2.body": "Ce silence choisi a produit l'effet inverse — chaque sortie devient un événement dont on parle précisément parce qu'on ne l'a pas vu venir. Elle ne subit plus le cycle de l'industrie ; elle le définit à son rythme.",
    "case.3.name": "BTS",
    "case.3.norm": "La K-pop, comme beaucoup d'industries musicales, cultive traditionnellement une image lissée et une rareté calculée — on aperçoit l'artiste, on ne le connaît pas.",
    "case.3.refuse": "BTS a construit l'inverse : un univers narratif suivi album après album, et une communication directe et quotidienne avec les fans, sans filtre d'agence entre les deux. Le risque était de perdre le mystère qui, dans ce secteur, entretient généralement le désir.",
    "case.3.body": "La communauté qui en est née ne se contente pas d'écouter — elle se sent coautrice de l'histoire, ce qui a construit une fidélité qu'aucune campagne publicitaire ne peut acheter.",
    "tour.out": "Vous avez déjà tout ce qu'il faut. Ce qui manque, c'est une identité pour le rendre visible.",
    "hero.kicker": "Architecture narrative · Artistes & fondateurs",
    "mq.1": "Musiciens",
    "mq.2": "Réalisateurs",
    "mq.3": "Fondateurs",
    "mq.4": "Auteurs",
    "mq.5": "Photographes",
    "mq.6": "Créateurs",
    "hero.tag": "Quelqu'un de moins doué<br/><b>a l'audience que vous méritez.</b>",
    "man.eyebrow": "Le constat",
    "man.body": "<b>Quelqu'un de moins doué que vous a l'audience que vous méritez.</b> Il ne produit pas mieux. Il ne travaille pas plus. Il se raconte mieux — et un public qui découvre cent noms par semaine ne retient que ceux qu'il peut nommer.",
    "man.body2": "Votre travail est bon, les retours le disent. Mais chaque sortie repart de zéro dans la tête de ceux qui vous suivent, parce que rien ne relie la précédente à la suivante. <em>Votre fil n'a jamais été écrit.</em>",
    "focus.eyebrow": "La différence",
    "focus.title": "Publier, ou se raconter.",
    "focus.lead": "Le même nom, deux réalités. Prenez la poignée et tirez : à gauche on publie sans fil conducteur, à droite le récit est écrit et chaque sortie s'appuie sur la précédente.",
    "focus.bad.tag": "Un nom qui publie",
    "focus.bad.big": "Chaque sortie repart de zéro. Le public découvre à chaque fois, au lieu d'attendre.",
    "focus.good.tag": "Un nom qui se raconte",
    "focus.good.big": "Le fil est écrit. Chaque sortie confirme la précédente au lieu de repartir de zéro. Tout se ressemble, sans se répéter.",
    "faq.title": "Ce que les artistes nous demandent.",
    "st.1.t": "Nous lisons tout ce que vous avez sorti.",
    "st.1.d": "Vos projets, vos textes, vos visuels, vos interviews — et ce que la presse retient quand elle vous résume en une phrase. Le fil est déjà là ; personne ne l'a nommé.",
    "st.1.b1": "Questionnaire d'entrée adapté à votre pratique",
    "st.1.b2": "Lecture de vos sorties et de ce qu'on en dit",
    "st.2.t": "Nous cartographions votre zone.",
    "st.2.d": "Trois à cinq artistes à qui on vous compare, ou dont vous partagez le public. Pas vos influences : ceux qui occupent le terrain que vous visez.",
    "st.2.b1": "Autopsie de la bio de chacun",
    "st.2.b2": "Ce que vous partagez sans le vouloir",
    "st.2.b3": "La place qui reste libre",
    "st.3.t": "Nous nommons votre fil.",
    "st.3.d": "Pas ce que vous voulez qu'il raconte : ce que le public en retient. L'écart explique pourquoi vos sorties ne s'additionnent pas.",
    "st.3.b1": "Le fil réel, sous vos projets",
    "st.3.b2": "Ce qui vous rend confondable",
    "st.3.b3": "Ce que votre bio dit avant vous",
    "st.4.t": "Nous donnons les mouvements.",
    "st.4.d": "Trois à cinq mouvements, dans l'ordre de priorité, avec ce que chacun coûte et ce qu'il débloque.",
    "st.4.b1": "Les mouvements à faire, dans l'ordre",
    "st.4.b2": "Ceux à refuser, et pourquoi",
    "st.4.b3": "Ce qu'il faut cesser de dire, et pourquoi",
    "st.5.t": "Nous vous laissons le document.",
    "st.5.d": "Vingt à trente pages, écrites à la main, utilisables seul comme avec votre label ou votre agent.",
    "st.5.b1": "Un document relisable et transmissible",
    "st.5.b2": "Aucun abonnement, aucune dépendance",
    "st.title": "On lit, on compare, on tranche.",
    "st.eyebrow": "L'Architecture · la méthode S.T.R.A.W.",
    "st.hint": "Faites glisser",
    "who.title": "Le studio qui écrit votre nom.",
    "f.required": "Champ requis",
    "who.body2": "Pas d'équipe, pas de sous-traitance, pas d'intermédiaire. Ceux qui lisent votre travail sont ceux qui écrivent le document.",
    "cta.title": "Racontez-nous votre travail.",
    "contact.title": "Votre travail a déjà tout. Écrivons-le.",
    "f.place": "Nom d'artiste ou nom propre",
    "f.type": "Pratique",
    "f.opt.r": "Musique",
    "f.opt.b": "Image et cinéma",
    "f.opt.c": "Écriture",
    "f.opt.cs": "Autre",
    "f.message": "Où en êtes-vous aujourd'hui, et qu'aimeriez-vous que le public comprenne de vous ?",
    "foot.tagline": "On écrit ce que votre nom raconte, et on vous donne de quoi le tenir.",
    "nav.services": "L'Architecture",
    "for.yes.1": "Vous êtes artiste, réalisateur, auteur, photographe ou fondateur, et votre nom doit porter votre travail.",
    "for.no.1": "Vous cherchez un attaché de presse ou un agent.",
    "for.yes.2": "Il existe au moins deux ou trois sorties publiques à lire.",
    "for.no.2": "Vous n'avez encore rien publié : il n'y a pas de matière.",
    "for.yes.3": "Chaque sortie repart de zéro dans la tête du public : rien ne relie la précédente à la suivante.",
    "for.no.3": "Vous voulez une identité visuelle ou un site vitrine.",
    "faq.1.q": "Pourquoi pas un attaché de presse ?",
    "faq.1.a": "Un attaché de presse diffuse un récit. Il ne l'écrit pas. L'Architecture vous donne ce qu'il diffusera, et il travaillera mieux avec.",
    "faq.2.q": "Je débute, est-ce trop tôt ?",
    "faq.2.a": "S'il existe au moins deux ou trois sorties à lire, non. S'il n'y a rien encore, oui : il n'y a pas de matière à lire, et nous vous le dirons.",
    "faq.3.q": "J'ai aussi une marque, un projet ou un lieu ?",
    "faq.3.a": "C'est fréquent. La méthode, le prix et le délai ne changent pas : l'Architecture porte sur votre nom, et ce qui relie vos projets s'y écrit. Dites-nous dans le questionnaire ce que vous menez. Si vos projets n'ont rien en commun, écrivez-nous avant de commander.",
    "faq.7.q": "Et si le diagnostic ne m'apprend rien ?",
    "faq.7.a": "Alors nous vous le disons, et c'est une réponse en soi : le fil est déjà lisible, ne le forcez pas. Ça arrive rarement : ce qu'un artiste croit évident dans son travail n'apparaît presque jamais dans ce que le public en retient, et c'est cet écart que le document mesure. Dans ce cas, vous saurez que le problème est ailleurs, et où le chercher.",
    "faq.8.q": "Qu'est-ce que je garde à la fin ?",
    "faq.8.a": "Tout, sans abonnement. Le document est à vous, avec un droit d'usage commercial illimité et perpétuel : votre fil nommé, la carte de votre zone, les mouvements hiérarchisés et ce qu'il faut cesser de dire.",
    "cta.lead": "2 900 €, livré en trois semaines, ou remboursé. Un document écrit pour votre nom, à vous pour toujours.",
  },
  en: {
    "case.normLabel": "What the industry does",
    "case.refuseLabel": "What it did",
    "case.resultLabel": "What it earned",
    "case.eyebrow": "What it looks like elsewhere",
    "case.title": "Three names that decided.",
    "case.lead": "None of them were built by us. All three did, at their scale, what this Architecture does for you.",
    "case.1.name": "Travis Scott",
    "case.1.norm": "Most artists who succeed in one field stay there, to avoid diluting their recognition.",
    "case.1.refuse": "Travis Scott built the same visual and sonic universe — chaotic, saturated, almost cinematic — across his albums, his clothing lines, and a collaboration inside a video game played by hundreds of millions of people. Each new ground was a risk: losing coherence, or worse, losing credibility in a field that isn't his own.",
    "case.1.body": "The opposite happened, because the universe, not the medium, became the signature. A Travis Scott project is recognisable before a single sound plays.",
    "case.2.name": "Beyoncé",
    "case.2.norm": "The music industry runs on a well-worn ritual — announcement, singles, interviews, months of promotional touring.",
    "case.2.refuse": "Beyoncé chose, more than once, to release a full album with no warning, no lead single, no interviews. The risk was direct: no advance media buildup to carry sales.",
    "case.2.body": "That chosen silence produced the opposite effect — each release becomes an event people talk about precisely because they never saw it coming. She no longer follows the industry's cycle; she sets it on her own terms.",
    "case.3.name": "BTS",
    "case.3.norm": "K-pop, like many music industries, traditionally cultivates a polished image and calculated scarcity — you glimpse the artist, you don't know them.",
    "case.3.refuse": "BTS built the opposite: a narrative universe followed album after album, and direct, daily communication with fans, with no agency filter between the two. The risk was losing the mystery that, in this industry, usually sustains desire.",
    "case.3.body": "The community that grew from it doesn't just listen — it feels like a co-author of the story, which built a loyalty no advertising campaign can buy.",
    "tour.out": "You already have everything you need. What is missing is an identity to make it visible.",
    "hero.kicker": "Narrative architecture · Artists & founders",
    "mq.1": "Musicians",
    "mq.2": "Directors",
    "mq.3": "Founders",
    "mq.4": "Writers",
    "mq.5": "Photographers",
    "mq.6": "Makers",
    "hero.tag": "Someone less gifted<br/><b>has the audience you deserve.</b>",
    "man.eyebrow": "The finding",
    "man.body": "<b>Someone less gifted than you has the audience you deserve.</b> They do not make better work. They do not work harder. They tell it better — and an audience discovering a hundred names a week only keeps the ones it can name.",
    "man.body2": "Your work is good, the feedback says so. But every release starts from zero in the minds of those who follow you, because nothing links the last one to the next. <em>Your thread has never been written.</em>",
    "focus.eyebrow": "The difference",
    "focus.title": "Posting, or telling.",
    "focus.lead": "The same name, two realities. Take the handle and pull.",
    "focus.bad.tag": "A name that posts",
    "focus.bad.big": "Every release starts from zero. The audience discovers you each time instead of waiting for you.",
    "focus.good.tag": "A name that tells its story",
    "focus.good.big": "The thread is written. Each release confirms the last and sets up the next.",
    "faq.title": "What artists ask us.",
    "st.1.t": "We read everything you have put out.",
    "st.1.d": "Your projects, your writing, your visuals, your interviews — and what the press keeps when it sums you up.",
    "st.1.b1": "An entry questionnaire matched to your practice",
    "st.1.b2": "A reading of your releases and what is said about them",
    "st.2.t": "We map your lane.",
    "st.2.d": "Three to five artists you get compared to, or whose audience you share. Not your influences.",
    "st.2.b1": "An autopsy of each of their bios",
    "st.2.b2": "What you share without meaning to",
    "st.2.b3": "The place left open",
    "st.3.t": "We name your thread.",
    "st.3.d": "Not what you want it to say: what the audience keeps. The gap explains why your releases do not add up.",
    "st.3.b1": "The real thread, under your projects",
    "st.3.b2": "What makes you mistakable",
    "st.3.b3": "What your bio says before you do",
    "st.4.t": "We hand over the moves.",
    "st.4.d": "Three to five moves, ranked, with what each one costs and unlocks.",
    "st.4.b1": "The moves to make, in order",
    "st.4.b2": "The ones to refuse, and why",
    "st.4.b3": "What to stop saying",
    "st.5.t": "We leave you the document.",
    "st.5.d": "Twenty to thirty pages, written by hand, usable alone or with your label or agent.",
    "st.5.b1": "A document you can re-read and pass on",
    "st.5.b2": "No subscription, no dependency",
    "st.title": "We read, we compare, we settle.",
    "st.eyebrow": "The Architecture · the S.T.R.A.W. method",
    "st.hint": "Drag across",
    "who.title": "The studio that writes your name.",
    "f.required": "Required field",
    "who.body2": "No team, no subcontracting, no middleman. The people who read your work are the people who write the document.",
    "cta.title": "Tell us about your work.",
    "contact.title": "Your work already has everything. Let's write it.",
    "f.place": "Artist name or own name",
    "f.type": "Practice",
    "f.opt.r": "Music",
    "f.opt.b": "Image and film",
    "f.opt.c": "Writing",
    "f.opt.cs": "Other",
    "f.message": "Where are you today, and what would you like the audience to understand about you?",
    "foot.tagline": "We write what your name says, and hand you what you need to hold it.",
    "nav.services": "The Architecture",
    "for.yes.1": "You are an artist, filmmaker, author, photographer or founder, and your name has to carry your work.",
    "for.no.1": "You are looking for a press agent or a booking agent.",
    "for.yes.2": "There are at least two or three public releases to read.",
    "for.no.2": "You have published nothing yet: there is no material.",
    "for.yes.3": "Each release starts from zero in the audience's mind: nothing links one to the next.",
    "for.no.3": "You want a visual identity or a showcase website.",
    "faq.1.q": "Why not a press agent?",
    "faq.1.a": "A press agent circulates a story. They do not write it. The Architecture gives them what to circulate, and they will work better with it.",
    "faq.2.q": "I am just starting out. Is it too early?",
    "faq.2.a": "If there are at least two or three releases to read, no. If there is nothing yet, yes: there is no material to read, and we will tell you so.",
    "faq.3.q": "I also have a brand, a project or a venue.",
    "faq.3.a": "That is common. The method, the price and the deadline do not change: the Architecture covers your name, and what links your projects is written into it. Tell us in the questionnaire what you run. If your projects have nothing in common, write to us before ordering.",
    "faq.7.q": "What if the diagnosis teaches me nothing?",
    "faq.7.a": "Then we tell you so, and that is an answer in itself: the thread already reads, do not force it. It happens rarely: what an artist finds obvious in their work almost never matches what the audience keeps, and that gap is what the document measures. In that case you will know the problem lies elsewhere, and where to look.",
    "faq.8.q": "What do I keep at the end?",
    "faq.8.a": "Everything, with no subscription. The document is yours, with unlimited and perpetual commercial use: your thread named, the map of your lane, the ranked moves and what to stop saying.",
    "cta.lead": "€2,900, delivered in three weeks, or refunded. A document written for your name, yours for good.",
  },
}

export default function NameTerrainPage() {
  return <TerrainPage copy={COPY} />
}
