import type { Metadata } from "next"
import { TerrainPage, type TerrainCopy } from "@/components/terrain/terrain-page"

/**
 * THE NAME — le terrain artistes & fondateurs.
 *
 * Même page que THE ROOM et BRAND : même HTML, même CSS, même JavaScript.
 * Seul le dictionnaire change.
 *
 * Remplace l'ancienne page /artistes, qui portait la mise en page de
 * MOMENTUM — une charte de plus à maintenir, pour un terrain qui n'avait
 * aucune raison d'avoir la sienne.
 */

export const metadata: Metadata = {
  title: "THE NAME — L'architecture narrative pour les artistes et les fondateurs",
  description:
    "Vos sorties ne s'additionnent pas. L'architecture narrative dit ce que votre nom raconte aujourd'hui et donne les mouvements qui font tenir le fil.",
}

const COPY: TerrainCopy = {
  slug: "the-name",
  wordmark: "THE NAME",
  fr: {
    "ex.eyebrow": "Un cas",
    "ex.title": "Ce qu'on a livré à ORVAL, et ce que ça a changé.",
    "ex.head": "Architecture narrative · Noms propres",
    "ex.house": "ORVAL",
    "ex.lead": "ORVAL, producteur de musique électronique, quatre EP en six ans. Le nom est changé, les livrables ne le sont pas.",
    "ex.foot": "Six pièces livrées. Quatre montrées ici.",
    "ex.1.n": "Pièce 01",
    "case.eyebrow": "Ce que ça donne, ailleurs",
    "case.title": "Trois noms qui ont tranché.",
    "case.lead": "Aucun n'a été construit par nous. Tous les trois ont fait, à leur échelle, ce que cette Architecture fait pour vous.",
    "case.1.name": "Travis Scott",
    "case.1.body": "A refusé de rester dans la musique. Un même univers visuel et sonore traverse ses albums, la mode et le jeu vidéo, sans jamais se diluer — un pari risqué à chaque nouveau terrain, où suivre les codes existants aurait été plus sûr. C'est ce refus de se limiter à un seul médium qui fait qu'on reconnaît son univers avant même d'entendre un titre.",
    "case.2.name": "Beyoncé",
    "case.2.body": "A refusé le cycle promotionnel classique. Sorties surprises, silence médiatique choisi : elle tient elle-même le récit, du début à la fin, là où l'industrie entière pousse vers l'omniprésence et l'interview permanente. Ce refus de se rendre disponible est devenu la preuve de son autorité sur sa propre image.",
    "case.3.name": "BTS",
    "case.3.body": "A refusé la distance habituelle entre un artiste et son public. Un univers narratif suivi et une communication directe et continue avec les fans, quand la norme du genre reposait sur la rareté calculée et l'image lissée. Ce refus d'un contrôle distant a construit une communauté qui se sent coautrice de l'histoire, pas simple spectatrice.",
    "deliv.eyebrow": "Ce que vous recevez, précisément",
    "deliv.title": "Les six pièces, pour vous.",
    "deliv.lead": "Le même document que pour n'importe quel nom, mais rien de générique dedans.",
    "deliv.1.t": "La plateforme",
    "deliv.1.d": "Le personnage public que vous incarnez — ce qui vous distingue d'un autre artiste qui ferait la même chose.",
    "deliv.2.t": "Le diagnostic",
    "deliv.2.d": "Vos interviews, votre bio, vos réseaux dépouillés — ce que vous dites de vous quand on vous le demande, et ce que ça tait.",
    "deliv.3.t": "La carte",
    "deliv.3.d": "Les autres noms auxquels on vous compare, disséqués un par un, et la place qu'aucun d'eux ne peut occuper à votre place.",
    "deliv.4.t": "Les décisions",
    "deliv.4.d": "Ce qu'il faut changer en premier dans votre image publique — avant une sortie, avant une campagne — et ce que ça fait perdre.",
    "deliv.5.t": "Les playbooks",
    "deliv.5.d": "Ce que votre équipe répond à un journaliste, ce que vous postez la veille d'une sortie, comment votre entourage parle de vous en votre absence.",
    "deliv.6.t": "Le langage",
    "deliv.6.d": "Votre biographie en trois longueurs, vos textes de présentation, le lexique qui vous rend reconnaissable dans une interview sans qu'on ait besoin de voir votre visage.",
    "ex.1.k": "La plateforme",
    "ex.1.b": "Une raison d'être, un positionnement, trois partis pris formulés en refus, et un ton de voix pour les textes de sortie. Sept pages.",
    "ex.1.pk": "Ce que ça a changé",
    "ex.1.pv": "Le troisième parti pris — ne jamais ouvrir un projet sur un instrument — a servi à écarter deux propositions de collaboration qui auraient dilué le fil.",
    "ex.2.n": "Pièce 03",
    "ex.2.k": "La carte de la zone",
    "ex.2.b": "Les cinq noms que la presse cite à côté du sien, leur bio citée mot pour mot, et le relevé des mots partagés. Le constat : « atmosphérique » chez quatre, « cinématographique » chez trois, le lieu réel revendiqué par aucun.",
    "ex.2.pk": "Ce que ça a changé",
    "ex.2.pv": "La bio a cessé d'annoncer « des textures organiques », formule présente dans quatorze des vingt bios comparées. Elle ouvre désormais sur l'enregistrement de terrain.",
    "ex.3.n": "Pièce 04",
    "ex.3.k": "Les décisions",
    "ex.3.b": "Quatre mouvements ordonnés. Le premier : réécrire la première ligne de la bio autour de la méthode, avec la formulation exacte, sur les trois plateformes.",
    "ex.3.pk": "Ce que ça a changé",
    "ex.3.pv": "Deux chroniques de la sortie suivante ont repris la formulation mot pour mot. Les trois précédentes décrivaient déjà le geste sans pouvoir le nommer — la phrase leur manquait.",
    "ex.4.n": "Pièce 05",
    "ex.4.k": "Les playbooks",
    "ex.4.b": "Cinq playbooks. Celui des réseaux contient le format tenable entre deux projets. Celui de la presse contient la phrase de présentation en trois longueurs.",
    "ex.4.pk": "Ce que ça a changé",
    "ex.4.pv": "Le dossier de presse du cinquième EP a été envoyé sans être réécrit. Son attaché de presse a repris le texte tel quel.",
    "tour.out": "Vous avez déjà tout ce qu'il faut. Ce qui manque, c'est une identité pour le rendre visible.",
    "hero.kicker": "Architecture narrative · Artistes & fondateurs",
    "mq.1": "Musiciens",
    "mq.2": "Réalisateurs",
    "mq.3": "Fondateurs",
    "mq.4": "Auteurs",
    "mq.5": "Photographes",
    "mq.6": "Créateurs",
    "hero.tag": "Quelqu'un de moins doué<br/><b>a l'audience que vous méritez.</b>",
    "man.eyebrow": "Le constat",
    "man.body": "<b>Quelqu'un de moins doué que vous a l'audience que vous méritez.</b> Il ne produit pas mieux. Il ne travaille pas plus. Il se raconte mieux — et un public qui découvre cent noms par semaine ne retient que ceux qu'il peut nommer.",
    "man.body2": "Votre travail est bon, les retours le disent. Mais chaque sortie repart de zéro dans la tête de ceux qui vous suivent, parce que rien ne relie la précédente à la suivante. <em>Votre fil n'a jamais été écrit.</em>",
    "focus.eyebrow": "La différence",
    "focus.title": "Publier, ou se raconter.",
    "focus.lead": "Le même nom, deux réalités. Prenez la poignée et tirez : à gauche on publie sans fil conducteur, à droite le récit est écrit et chaque sortie s'appuie sur la précédente.",
    "focus.bad.tag": "Un nom qui publie",
    "focus.bad.big": "Chaque sortie repart de zéro. Le public découvre à chaque fois, au lieu d'attendre.",
    "focus.good.tag": "Un nom qui se raconte",
    "focus.good.big": "Le fil est écrit. Chaque sortie confirme la précédente au lieu de repartir de zéro. Tout se ressemble, sans se répéter.",
    "faq.title": "Ce que les artistes nous demandent.",
    "faq.1.q": "Pourquoi pas un attaché de presse ?",
    "faq.1.a": "Un attaché de presse diffuse un récit. Il ne l'écrit pas. L'Architecture vous donne ce qu'il diffusera — et il travaillera mieux avec.",
    "faq.2.q": "Je débute, est-ce trop tôt ?",
    "faq.2.a": "S'il existe au moins deux ou trois sorties à lire, non. S'il n'y a rien encore, oui : il n'y a pas de matière à lire, et nous vous le dirons.",
    "faq.3.q": "Combien de temps ça prend, de mon côté ?",
    "faq.3.a": "Quelques heures en tout. Un questionnaire d'entrée, un échange avec vous, et la remise du document. Le reste du travail se fait sans vous mobiliser.",
    "faq.4.q": "Et si le diagnostic ne m'apprend rien ?",
    "faq.4.a": "Alors nous vous le disons, et c'est une réponse en soi : le fil est déjà lisible, ne le forcez pas. Ça arrive rarement — ce qu'un artiste croit évident dans son travail n'apparaît presque jamais dans ce que le public en retient, et c'est cet écart que le document mesure. Dans ce cas, vous saurez que le problème est ailleurs, et où le chercher.",
    "faq.5.q": "Qu'est-ce que je garde à la fin ?",
    "faq.5.a": "Le document entier, pour toujours. Votre fil nommé, la carte de votre zone, les mouvements hiérarchisés et ce qu'il faut cesser de dire.",
    "st.1.t": "Nous lisons tout ce que vous avez sorti.",
    "st.1.d": "Vos projets, vos textes, vos visuels, vos interviews — et ce que la presse retient quand elle vous résume en une phrase. Le fil est déjà là ; personne ne l'a nommé.",
    "st.1.b1": "Questionnaire d'entrée adapté à votre pratique",
    "st.1.b2": "Lecture de vos sorties et de ce qu'on en dit",
    "st.2.t": "Nous cartographions votre zone.",
    "st.2.d": "Trois à cinq artistes à qui on vous compare, ou dont vous partagez le public. Pas vos influences : ceux qui occupent le terrain que vous visez.",
    "st.2.b1": "Autopsie de la bio de chacun",
    "st.2.b2": "Ce que vous partagez sans le vouloir",
    "st.2.b3": "La place qui reste libre",
    "st.3.t": "Nous nommons votre fil.",
    "st.3.d": "Pas ce que vous voulez qu'il raconte : ce que le public en retient. L'écart explique pourquoi vos sorties ne s'additionnent pas.",
    "st.3.b1": "Le fil réel, sous vos projets",
    "st.3.b2": "Ce qui vous rend confondable",
    "st.3.b3": "Ce que votre bio dit avant vous",
    "st.4.t": "Nous donnons les mouvements.",
    "st.4.d": "Trois à cinq mouvements, dans l'ordre de priorité, avec ce que chacun coûte et ce qu'il débloque.",
    "st.4.b1": "Les mouvements à faire, dans l'ordre",
    "st.4.b2": "Ceux à refuser, et pourquoi",
    "st.4.b3": "Ce qu'il faut cesser de dire, et pourquoi",
    "st.5.t": "Nous vous laissons le document.",
    "st.5.d": "Vingt à trente pages, écrites à la main, utilisables seul comme avec votre label ou votre agent.",
    "st.5.b1": "Un document relisable et transmissible",
    "st.5.b2": "Aucun abonnement, aucune dépendance",
    "st.title": "On lit, on compare, on tranche.",
    "st.eyebrow": "L'Architecture · la méthode S.T.R.A.W.",
    "st.hint": "Faites glisser",
    "price.b.d": "On lit votre nom comme le fait votre public : ce qu'il raconte aujourd'hui, ce qu'on en retient, et les mouvements qui changent ça. Un document de cinquante à soixante-dix pages, livré en trois semaines. La même Architecture que pour une marque ou un lieu.",
    "who.title": "Le studio qui écrit votre nom.",
    "f.required": "Champ requis",
    "price.a.d": "Elle exécute à votre place. Elle sait ce que votre nom raconte, vous non. Au bout de deux ans : environ 30 000 € dépensés, et rien qui vous appartienne.",
    "price.after": "Ensuite, si vous voulez qu'on écrive le récit complet et qu'on livre les vingt pièces qui le tiennent dans la durée : l'architecture narrative, 4 500 €.",
    "who.body2": "Pas d'équipe, pas de sous-traitance, pas d'intermédiaire. Ceux qui lisent votre travail sont ceux qui écrivent le document.",
    "cta.title": "Racontez-nous votre travail.",
    "cta.lead": "Vingt minutes suffisent pour savoir si votre nom a de quoi être écrit. Nous prenons peu de projets à la fois, et nous répondons nous-mêmes.",
    "contact.title": "Votre travail a déjà tout. Écrivons-le.",
    "f.place": "Nom d'artiste ou nom propre",
    "f.type": "Pratique",
    "f.opt.r": "Musique",
    "f.opt.b": "Image et cinéma",
    "f.opt.c": "Écriture",
    "f.opt.cs": "Autre",
    "f.message": "Où en êtes-vous aujourd'hui, et qu'aimeriez-vous que le public comprenne de vous ?",
    "foot.tagline": "On écrit ce que votre nom raconte, et on vous donne de quoi le tenir.",
    "nav.services": "L'Architecture",
  },
  en: {
    "ex.eyebrow": "A case",
    "ex.title": "What we delivered to ORVAL, and what it changed.",
    "ex.head": "Narrative architecture · Names",
    "ex.house": "ORVAL",
    "ex.lead": "ORVAL, electronic music producer, four EPs in six years. The name is changed, the deliverables are not.",
    "ex.foot": "Six pieces delivered. Four shown here.",
    "ex.1.n": "Piece 01",
    "case.eyebrow": "What it looks like elsewhere",
    "case.title": "Three names that decided.",
    "case.lead": "None of them were built by us. All three did, at their scale, what this Architecture does for you.",
    "case.1.name": "Travis Scott",
    "case.1.body": "Refused to stay inside music. The same visual and sonic universe runs through his albums, fashion, and gaming, without ever thinning out — a risky bet on each new ground, where following existing codes would have been safer. That refusal to stay in one medium is why his universe is recognisable before a single track plays.",
    "case.2.name": "Beyoncé",
    "case.2.body": "Refused the standard promotional cycle. Surprise releases, chosen media silence — she holds the narrative herself, start to finish, while the whole industry pushes toward omnipresence and endless interviews. That refusal to be available became the proof of her own authority over her image.",
    "case.3.name": "BTS",
    "case.3.body": "Refused the usual distance between an artist and their audience. A followed narrative universe and direct, sustained communication with fans, when the genre's norm rested on calculated scarcity and a polished image. That refusal of distant control built a community that feels like a co-author of the story, not a spectator.",
    "deliv.eyebrow": "What you receive, precisely",
    "deliv.title": "The six pieces, for you.",
    "deliv.lead": "The same document as for any name, but nothing generic inside it.",
    "deliv.1.t": "The platform",
    "deliv.1.d": "The public character you embody — what sets you apart from another artist doing the same thing.",
    "deliv.2.t": "The diagnosis",
    "deliv.2.d": "Your interviews, your bio, your social pages gone through — what you say about yourself when asked, and what it leaves unsaid.",
    "deliv.3.t": "The map",
    "deliv.3.d": "The other names you get compared to, dissected one by one, and the ground none of them can occupy in your place.",
    "deliv.4.t": "The decisions",
    "deliv.4.d": "What to change first in your public image — before a release, before a campaign — and what it costs.",
    "deliv.5.t": "The playbooks",
    "deliv.5.d": "What your team answers a journalist, what you post the night before a release, how people around you talk about you when you're not in the room.",
    "deliv.6.t": "The language",
    "deliv.6.d": "Your biography at three lengths, your presentation copy, the lexicon that makes you recognisable in an interview without needing to see your face.",
    "ex.1.k": "The platform",
    "ex.1.b": "A purpose, a positioning, three commitments written as refusals, and a tone of voice for release copy. Seven pages.",
    "ex.1.pk": "What it changed",
    "ex.1.pv": "The third commitment — never open a project on an instrument — was used to turn down two collaborations that would have diluted the thread.",
    "ex.2.n": "Piece 03",
    "ex.2.k": "The map of the lane",
    "ex.2.b": "The five names the press quotes alongside his, their bio quoted word for word, and a record of shared words. The finding: “atmospheric” in four, “cinematic” in three, the real place claimed by none.",
    "ex.2.pk": "What it changed",
    "ex.2.pv": "The bio stopped announcing “organic textures”, a phrase found in fourteen of the twenty bios compared. It now opens on the field recording.",
    "ex.3.n": "Piece 04",
    "ex.3.k": "The decisions",
    "ex.3.b": "Four ordered moves. The first: rewrite the first line of the bio around the method, with the exact wording, across all three platforms.",
    "ex.3.pk": "What it changed",
    "ex.3.pv": "Two reviews of the next release quoted the wording word for word. The three previous ones already described the gesture without being able to name it — they were missing the sentence.",
    "ex.4.n": "Piece 05",
    "ex.4.k": "The playbooks",
    "ex.4.b": "Five playbooks. The social one holds the format he can sustain between projects. The press one holds the introduction at three lengths.",
    "ex.4.pk": "What it changed",
    "ex.4.pv": "The press kit for the fifth EP went out without being rewritten. His press officer used the text as it was.",
    "tour.out": "You already have everything you need. What is missing is an identity to make it visible.",
    "hero.kicker": "Narrative architecture · Artists & founders",
    "mq.1": "Musicians",
    "mq.2": "Directors",
    "mq.3": "Founders",
    "mq.4": "Writers",
    "mq.5": "Photographers",
    "mq.6": "Makers",
    "hero.tag": "Someone less gifted<br/><b>has the audience you deserve.</b>",
    "man.eyebrow": "The finding",
    "man.body": "<b>Someone less gifted than you has the audience you deserve.</b> They do not make better work. They do not work harder. They tell it better — and an audience discovering a hundred names a week only keeps the ones it can name.",
    "man.body2": "Your work is good, the feedback says so. But every release starts from zero in the minds of those who follow you, because nothing links the last one to the next. <em>Your thread has never been written.</em>",
    "focus.eyebrow": "The difference",
    "focus.title": "Posting, or telling.",
    "focus.lead": "The same name, two realities. Take the handle and pull.",
    "focus.bad.tag": "A name that posts",
    "focus.bad.big": "Every release starts from zero. The audience discovers you each time instead of waiting for you.",
    "focus.good.tag": "A name that tells its story",
    "focus.good.big": "The thread is written. Each release confirms the last and sets up the next.",
    "faq.title": "What artists ask us.",
    "faq.1.q": "Why not a press agent?",
    "faq.1.a": "A press agent circulates a story. They do not write it. The Architecture gives them what to circulate — and they will work better with it.",
    "faq.2.q": "I am starting out, is it too early?",
    "faq.2.a": "If there are at least two or three releases to read, no. If there is nothing yet, yes: there is no material to read, and we will tell you so.",
    "faq.3.q": "How much of my time does it take?",
    "faq.3.a": "About an hour. An entry questionnaire, then we work without taking your time. The document arrives within three weeks.",
    "faq.4.q": "What if the diagnosis teaches me nothing?",
    "faq.4.a": "Then we tell you so, and that is an answer in itself: the thread already reads, do not force it. It happens rarely — what an artist finds obvious in their work almost never matches what the audience keeps, and that gap is what the document measures. In that case you will know the problem lies elsewhere, and where to look.",
    "faq.5.q": "What do I keep at the end?",
    "faq.5.a": "The whole document, forever. Your thread named, the map of your lane, the ranked moves and what to stop saying.",
    "st.1.t": "We read everything you have put out.",
    "st.1.d": "Your projects, your writing, your visuals, your interviews — and what the press keeps when it sums you up.",
    "st.1.b1": "An entry questionnaire matched to your practice",
    "st.1.b2": "A reading of your releases and what is said about them",
    "st.2.t": "We map your lane.",
    "st.2.d": "Three to five artists you get compared to, or whose audience you share. Not your influences.",
    "st.2.b1": "An autopsy of each of their bios",
    "st.2.b2": "What you share without meaning to",
    "st.2.b3": "The place left open",
    "st.3.t": "We name your thread.",
    "st.3.d": "Not what you want it to say: what the audience keeps. The gap explains why your releases do not add up.",
    "st.3.b1": "The real thread, under your projects",
    "st.3.b2": "What makes you mistakable",
    "st.3.b3": "What your bio says before you do",
    "st.4.t": "We hand over the moves.",
    "st.4.d": "Three to five moves, ranked, with what each one costs and unlocks.",
    "st.4.b1": "The moves to make, in order",
    "st.4.b2": "The ones to refuse, and why",
    "st.4.b3": "What to stop saying",
    "st.5.t": "We leave you the document.",
    "st.5.d": "Twenty to thirty pages, written by hand, usable alone or with your label or agent.",
    "st.5.b1": "A document you can re-read and pass on",
    "st.5.b2": "No subscription, no dependency",
    "st.title": "We read, we compare, we settle.",
    "st.eyebrow": "The Architecture · the S.T.R.A.W. method",
    "st.hint": "Drag across",
    "price.b.d": "We read your name the way your audience does: what it says today, what people keep of it, and the moves that change that. A fifty to seventy page document, delivered in three weeks. The same Architecture as for a brand or a venue.",
    "who.title": "The studio that writes your name.",
    "f.required": "Required field",
    "price.a.d": "It executes in your place. It knows what your name says, you do not. After two years: roughly 30,000 € spent, and nothing that belongs to you.",
    "price.after": "Then, if you want the full story written and the twenty pieces that hold it over time: the narrative architecture, 4,500 €.",
    "who.body2": "No team, no subcontracting, no middleman. The people who read your work are the people who write the document.",
    "cta.title": "Tell us about your work.",
    "cta.lead": "Twenty minutes is enough to know whether your name has something worth writing. We take on few projects at a time, and we answer ourselves.",
    "contact.title": "Your work already has everything. Let's write it.",
    "f.place": "Artist name or own name",
    "f.type": "Practice",
    "f.opt.r": "Music",
    "f.opt.b": "Image and film",
    "f.opt.c": "Writing",
    "f.opt.cs": "Other",
    "f.message": "Where are you today, and what would you like the audience to understand about you?",
    "foot.tagline": "We write what your name says, and hand you what you need to hold it.",
    "nav.services": "The Architecture",
  },
}

export default function NameTerrainPage() {
  return <TerrainPage copy={COPY} />
}
