import type { Metadata } from "next"
import { TerrainPage, type TerrainCopy } from "@/components/terrain/terrain-page"

/**
 * THE PRODUCT — le terrain produits.
 *
 * Quatrième terrain, même gabarit que BRAND, THE ROOM et THE NAME : même
 * HTML, même CSS, même JavaScript. Seul le dictionnaire change.
 *
 * Distinct de BRAND, et la distinction tient : une marque se juge sur ce
 * qu'elle refuse, un produit sur ce qu'il a fallu accepter pour le faire
 * ainsi. Le premier vend une position, le second une intention de
 * conception.
 */

export const metadata: Metadata = {
  title: "THE PRODUCT — L'audit narratif pour les produits",
  description:
    "Votre produit est bon, mais en rayon il devient une ligne de caractéristiques. L'audit narratif dit ce qu'il raconte aujourd'hui et donne les mouvements qui le sortent de la comparaison.",
}

const COPY: TerrainCopy = {
  slug: "the-product",
  wordmark: "THE PRODUCT",
  fr: {
    "ex.3.pv": "Coût : 1 photo + 3 lignes, 0 € de production · Effet attendu : la comparaison passe du prix d'achat au coût sur dix ans · Écart à l'achat : 89 € contre 59 € · Écart sur dix ans, pièces comprises : à votre avantage · Priorité 1 sur 4",
    "ex.3.pk": "Coût et effet",
    "ex.2.pv": "Panel : 5 références au même prix, 3 enseignes · Argument principal : vitesse 4/5, design 1/5 · Réparabilité revendiquée 0/5 · Réparabilité réellement possible 3/5 · Pièces détachées vendues en ligne : vous seul, 6 références",
    "ex.2.pk": "Relevé",
    "ex.1.pv": "Fiche technique : 12 caractéristiques, aucune hiérarchie · Poids annoncé : 1,2 kg · Concurrents : 700 g, 740 g, 1,1 kg, 1,3 kg · Mentions du matériau comme choix : 0 · Mentions de durée de vie : 0",
    "ex.1.pk": "Relevé",
    "ex.head": "Audit narratif · Produits",
    "ex.house": "Cafetière M-01",
    "ex.lead": "Trois passages d'un audit sur une cafetière à filtre en inox, fabriquée en Franche-Comté. Le nom est changé, les relevés ne le sont pas. Mise en page d'origine.",
    "ex.1.n": "Relevé sur la fiche technique, l'emballage et la notice de montage.",
    "ex.2.n": "Rayon observé : cinq références au même prix, trois enseignes.",
    "ex.3.n": "Priorité 1 sur 4. Les trois autres mouvements suivent en pages 22 et 23.",
    "ex.foot": "Extrait des pages 4, 9 et 21 — le document en compte 24.",
    "ex.eyebrow": "Un extrait",
    "ex.title": "Un cas réel, avec ses preuves.",
    "ex.1.k": "Le diagnostic",
    "ex.1.b": "« Votre fiche annonce 1,2 kg parmi douze caractéristiques, entre la contenance et le diamètre du filtre. C'est un arbitrage, pas une donnée : vous avez refusé le corps en plastique pour que l'objet tienne vingt ans, et le poids en est la conséquence directe. Formulé en grammes au milieu d'une liste, il se compare — et vous perdez, puisque deux concurrents pèsent 700 g. Formulé comme un refus assumé, il ne se compare plus : il devient la preuve d'une décision que les autres n'ont pas prise. »",
    "ex.2.k": "La carte du rayon",
    "ex.2.b": "« Quatre concurrents sur cinq mènent avec la vitesse d'infusion, le cinquième avec le design italien. Aucun ne parle de réparabilité, alors que trois d'entre eux la permettent techniquement — ils ne la revendiquent simplement pas. C'est l'angle libre, et il est structurellement le vôtre : vous vendez déjà six pièces détachées en ligne, dont le joint et la résistance, et vous êtes le seul du panel à le faire. Cet argument existe dans votre catalogue, pas dans votre discours. »",
    "ex.3.k": "Le mouvement",
    "ex.3.b": "« Mouvement 1 : ouvrir la page produit sur la pièce détachée, pas sur l'objet fini. Une photo du joint à 4 €, avec la phrase qui va avec — \\u201etout ce qui s'use se remplace, et se vend ici\\u201c. Coût : une photo et trois lignes. Ce que ça débloque : l'acheteur cesse de comparer un prix d'achat de 89 € à un prix de 59 €, et commence à comparer un coût sur dix ans. Sur ce terrain-là, vous gagnez contre les cinq références du panel. »",
    "mq.1": "Objets",
    "mq.2": "Applications",
    "mq.3": "Collections",
    "mq.4": "Éditions",
    "mq.5": "Instruments",
    "mq.6": "Machines",
    "hero.tag": "Votre produit est bon. Ce qu'il raconte, personne ne l'a écrit.",
    "man.eyebrow": "Le constat",
    "man.body": "Votre produit est bien fait. Ceux qui l'utilisent le gardent. <b>Et pourtant</b>, en rayon ou sur une page de comparaison, il devient une ligne de caractéristiques à côté d'une autre — parce que rien ne dit pourquoi il a été fait comme ça. Pendant ce temps, un produit moins bon se vend deux fois plus cher. Il n'est pas mieux conçu. <b>Il se raconte mieux.</b>",
    "man.body2": "Vous n'avez pas un problème de fiche technique. Vous avez un problème d'intention. Un produit porte déjà un récit — une contrainte acceptée, un arbitrage, un refus de faire comme les autres. <b>Le vôtre n'a jamais été écrit.</b>",
    "focus.eyebrow": "La différence",
    "focus.title": "Lister, ou raconter.",
    "focus.lead": "Le même produit, deux réalités. Prenez la poignée et tirez : à gauche on liste des caractéristiques, à droite l'intention est écrite et chaque détail la confirme.",
    "focus.bad.tag": "Un produit qui liste",
    "focus.bad.big": "Une suite de caractéristiques. L'acheteur compare des chiffres, donc il compare des prix.",
    "focus.good.tag": "Un produit qui se raconte",
    "focus.good.big": "L'intention est écrite. Chaque choix de conception devient un argument au lieu d'une ligne de spec. Tout se tient, sans se répéter.",
    "faq.title": "Ce que les fabricants nous demandent.",
    "faq.1.q": "Pourquoi pas une agence au mois ?",
    "faq.1.a": "Parce qu'au bout de deux ans vous aurez payé environ 30 000 € sans rien garder. Ici vous payez 490 € une fois, et le document vous appartient.",
    "faq.2.q": "Ça marche pour une gamme entière ?",
    "faq.2.a": "Oui. L'audit porte sur l'intention commune à la gamme, pas sur une référence isolée — c'est ce qui fait qu'on reconnaît vos produits entre eux.",
    "faq.3.q": "Combien de temps ça prend, de mon côté ?",
    "faq.3.a": "Quelques heures en tout. Un questionnaire d'entrée, un échange avec vous, et la remise du document. Le reste du travail se fait sans vous mobiliser.",
    "faq.4.q": "Et si le diagnostic ne m'apprend rien ?",
    "faq.4.a": "Alors nous vous le disons, et c'est une réponse en soi : l'intention est déjà lisible, n'y touchez pas. Ça arrive rarement — ce qui vous semble évident dans vos choix de conception n'apparaît presque jamais sur la page produit ni sur l'emballage, et c'est cet écart que le document mesure. Dans ce cas, vous aurez économisé la refonte d'emballage que vous envisagiez.",
    "faq.5.q": "Qu'est-ce que je garde à la fin ?",
    "faq.5.a": "Le document entier, pour toujours. L'intention nommée, la carte du rayon, les mouvements hiérarchisés et ce qu'il faut cesser de dire.",
    "st.1.t": "On lit ce que le produit dit de lui-même.",
    "st.1.d": "La page produit, la fiche, l'emballage, les photos, la notice, et ce que les acheteurs en disent dans leurs avis. Le récit est déjà là, dans vos choix de conception ; personne ne l'a formulé.",
    "st.1.b1": "Questionnaire d'entrée adapté à votre produit",
    "st.1.b2": "Lecture de tout ce qui accompagne le produit aujourd'hui",
    "st.2.t": "On cartographie le rayon.",
    "st.2.d": "Trois à cinq produits concurrents, leur promesse exacte, et l'argument que chacun met en avant. C'est là qu'apparaît l'angle que personne ne prend — et c'est souvent celui de votre conception.",
    "st.2.b1": "Autopsie de la promesse de chaque produit",
    "st.2.b2": "L'argument que trois d'entre eux revendiquent déjà",
    "st.2.b3": "L'angle libre, et pourquoi il est libre",
    "st.3.t": "On dit ce que votre produit raconte.",
    "st.3.d": "Pas ce qu'il fait : ce qu'il signifie pour celui qui l'achète. L'écart entre les deux explique en général pourquoi on le compare au prix.",
    "st.3.b1": "L'intention réelle, sous les caractéristiques",
    "st.3.b2": "Ce qui vous rend interchangeable",
    "st.3.b3": "Ce que votre packaging dit avant vous",
    "st.4.t": "On donne les mouvements.",
    "st.4.d": "Trois à cinq mouvements, dans l'ordre de priorité, avec ce que chacun coûte et ce qu'il débloque.",
    "st.4.b1": "Les mouvements à faire, hiérarchisés",
    "st.4.b2": "Ceux à refuser, et pourquoi",
    "st.4.b3": "Ce qu'il faut cesser de dire, et pourquoi",
    "st.5.t": "Nous vous laissons le document.",
    "st.5.d": "Vingt à trente pages, écrites à la main, utilisables par votre équipe produit comme par vos revendeurs.",
    "st.5.b1": "Un document relisable et transmissible",
    "st.5.b2": "Aucun abonnement, aucune dépendance",
    "st.title": "On lit, on compare, on tranche.",
    "st.eyebrow": "L'audit",
    "st.hint": "Faites glisser",
    "hero.kicker": "Audit narratif · Produits",
    "price.a.d": "Elle exécute à votre place. Elle sait ce que votre produit raconte, vous non. Au bout de deux ans : environ 30 000 € dépensés, et rien qui vous appartienne.",
    "price.b.d": "On lit votre produit comme le fait l'acheteur : ce qu'il raconte aujourd'hui, ce qu'on en retient, et les mouvements qui changent ça. Un document de vingt à trente pages, livré en sept jours. Le même audit que pour une marque, un lieu ou un nom.",
    "price.after": "Ensuite, si vous voulez qu'on écrive le récit complet et qu'on livre les vingt pièces qui le tiennent : l'architecture narrative, 4 500 €.",
    "who.title": "Le studio qui écrit votre produit.",
    "who.body2": "Pas d'équipe, pas de sous-traitance, pas d'intermédiaire. Ceux qui lisent votre produit sont ceux qui écrivent le document.",
    "cta.title": "Racontez-nous votre produit.",
    "cta.lead": "Vingt minutes suffisent pour savoir si votre produit a de quoi être écrit. Nous prenons peu de projets à la fois, et nous répondons nous-mêmes.",
    "contact.title": "Votre produit a déjà tout. Écrivons-le.",
    "f.place": "Nom du produit",
    "f.type": "Type de produit",
    "f.opt.r": "Objet physique",
    "f.opt.b": "Produit numérique",
    "f.opt.c": "Collection ou gamme",
    "f.opt.cs": "Autre",
    "f.message": "Où en êtes-vous aujourd'hui, et qu'aimeriez-vous qu'on comprenne de votre produit ?",
    "f.required": "Champ requis",
    "foot.tagline": "On écrit ce que votre produit raconte, et on vous donne de quoi le tenir.",
    "nav.services": "L'audit",
  },
  en: {
    "ex.3.pv": "Cost: 1 photo + 3 lines, €0 production · Expected effect: comparison shifts from purchase price to ten-year cost · Purchase gap: €89 vs €59 · Ten-year gap, parts included: in your favour · Priority 1 of 4",
    "ex.3.pk": "Cost and effect",
    "ex.2.pv": "Panel: 5 references at the same price, 3 retailers · Lead argument: speed 4/5, design 1/5 · Repairability claimed 0/5 · Actually possible 3/5 · Spare parts sold online: you only, 6 references",
    "ex.2.pk": "Evidence",
    "ex.1.pv": "Spec sheet: 12 features, no hierarchy · Stated weight: 1.2 kg · Competitors: 700 g, 740 g, 1.1 kg, 1.3 kg · Material framed as a choice: 0 · Lifespan mentions: 0",
    "ex.1.pk": "Evidence",
    "ex.head": "Narrative audit · Products",
    "ex.house": "M-01 coffee maker",
    "ex.lead": "Three passages from an audit on a stainless steel filter coffee maker, made in eastern France. The name is changed, the findings are not. Original layout.",
    "ex.1.n": "Taken from the spec sheet, the packaging and the assembly manual.",
    "ex.2.n": "Shelf observed: five references at the same price, three retailers.",
    "ex.3.n": "Priority 1 of 4. The other three moves follow on pages 22 and 23.",
    "ex.foot": "Excerpt from pages 4, 9 and 21 — the document runs to 24.",
    "ex.eyebrow": "An excerpt",
    "ex.title": "A real case, with its evidence.",
    "ex.1.k": "The diagnosis",
    "ex.1.b": "\\u201cYour spec sheet lists 1.2 kg among twelve features, between capacity and filter diameter. It is a trade-off, not a data point: you refused a plastic body so the object would last twenty years, and the weight is the direct consequence. Stated in grams inside a list, it invites comparison — and you lose, since two competitors weigh 700 g. Stated as an owned refusal, it stops being comparable: it becomes proof of a decision the others did not make.\\u201d",
    "ex.2.k": "The map of the shelf",
    "ex.2.b": "\\u201cFour competitors out of five lead with brew speed, the fifth with Italian design. None mentions repairability, although three of them technically allow it — they simply do not claim it. That is the open angle, and it is structurally yours: you already sell six spare parts online, including the gasket and the heating element, and you are the only one in the panel doing so. The argument exists in your catalogue, not in your words.\\u201d",
    "ex.3.k": "The move",
    "ex.3.b": "\\u201cMove 1: open the product page on the spare part, not the finished object. A photo of the €4 gasket, with the line that goes with it — \\u2018everything that wears out can be replaced, and is sold here\\u2019. Cost: one photo and three lines. What it unlocks: the buyer stops comparing an €89 purchase price to a €59 one, and starts comparing a ten-year cost. On that ground you beat all five references in the panel.\\u201d",
    "mq.1": "Objects",
    "mq.2": "Apps",
    "mq.3": "Collections",
    "mq.4": "Editions",
    "mq.5": "Instruments",
    "mq.6": "Machines",
    "hero.tag": "Your product is good.<br/><b>What it says has never been written.</b>",
    "man.eyebrow": "The finding",
    "man.body": "Your product is well made, the people who use it keep it. <b>And yet</b>, on a shelf it becomes one line of specs next to another.",
    "man.body2": "This is not a spec sheet problem, it is an intent problem. A product already carries a story — a constraint accepted, a trade-off. <b>Yours has never been written.</b>",
    "focus.eyebrow": "The difference",
    "focus.title": "Listing, or telling.",
    "focus.lead": "The same product, two realities. Take the handle and pull.",
    "focus.bad.tag": "A product that lists",
    "focus.bad.big": "A run of specifications. The buyer compares numbers, so the buyer compares prices.",
    "focus.good.tag": "A product that tells its story",
    "focus.good.big": "The intent is written. Every design choice becomes an argument instead of a spec line.",
    "faq.title": "What makers ask us.",
    "faq.1.q": "Why not a monthly agency?",
    "faq.1.a": "Because after two years you will have spent around 30,000 € and kept nothing. Here you pay 490 € once, and the document is yours.",
    "faq.2.q": "Does it work for a whole range?",
    "faq.2.a": "Yes. The audit covers the intent shared across the range, not a single reference — that is what makes your products recognisable as a family.",
    "faq.3.q": "How much of my time does it take?",
    "faq.3.a": "About an hour. An entry questionnaire, then we work without taking your time. The document arrives within seven to fourteen days.",
    "faq.4.q": "What if the diagnosis teaches me nothing?",
    "faq.4.a": "Then we tell you so, and that is an answer in itself: the intent already reads, leave it alone. It happens rarely — what seems obvious to you in your design choices almost never shows up on the product page or the packaging, and that gap is what the document measures. In that case you will have saved the packaging redesign you were considering.",
    "faq.5.q": "What do I keep at the end?",
    "faq.5.a": "The whole document, forever. The intent named, the map of the shelf, the ranked moves and what to stop saying.",
    "st.1.t": "We read what the product says about itself.",
    "st.1.d": "The product page, the spec sheet, the packaging, the manual — and what buyers say in their reviews.",
    "st.1.b1": "An entry questionnaire matched to your product",
    "st.1.b2": "A reading of everything that surrounds it",
    "st.2.t": "We map the shelf.",
    "st.2.d": "Three to five competing products, their exact promise, and the argument each one leads with.",
    "st.2.b1": "An autopsy of each competitor's promise",
    "st.2.b2": "The argument three of them claim",
    "st.2.b3": "The angle nobody takes",
    "st.3.t": "We name its intent.",
    "st.3.d": "Not what it does: what it means to the person buying it. The gap explains why it gets compared on price.",
    "st.3.b1": "The real intent, under the specs",
    "st.3.b2": "What makes you interchangeable",
    "st.3.b3": "What your packaging says before you do",
    "st.4.t": "We hand over the moves.",
    "st.4.d": "Three to five moves, ranked, with what each one costs and unlocks.",
    "st.4.b1": "The moves to make, in order",
    "st.4.b2": "The ones to refuse, and why",
    "st.4.b3": "What to stop saying",
    "st.5.t": "We leave you the document.",
    "st.5.d": "Twenty to thirty pages, written by hand, usable by your product team and your resellers alike.",
    "st.5.b1": "A document you can re-read and pass on",
    "st.5.b2": "No subscription, no dependency",
    "st.title": "We read, we compare, we settle.",
    "st.eyebrow": "The audit",
    "st.hint": "Drag across",
    "hero.kicker": "Narrative audit · Products",
    "price.a.d": "It executes in your place. It knows what your product says, you do not. After two years: roughly 30,000 € spent, and nothing that belongs to you.",
    "price.b.d": "We read your product the way the buyer does: what it says today, what people keep of it, and the moves that change that. A twenty to thirty page document, delivered in seven days. The same audit as for a brand, a venue or a name.",
    "price.after": "Then, if you want the full story written and the twenty pieces that hold it: the narrative architecture, 4,500 €.",
    "who.title": "The studio that writes your product.",
    "who.body2": "No team, no subcontracting, no middleman. The people who read your product are the people who write the document.",
    "cta.title": "Tell us about your product.",
    "cta.lead": "Twenty minutes is enough to know whether your product has something worth writing. We take on few projects at a time, and we answer ourselves.",
    "contact.title": "Your product already has everything. Let's write it.",
    "f.place": "Product name",
    "f.type": "Type of product",
    "f.opt.r": "Physical object",
    "f.opt.b": "Digital product",
    "f.opt.c": "Collection or range",
    "f.opt.cs": "Other",
    "f.message": "Where are you today, and what would you like people to understand about your product?",
    "f.required": "Required field",
    "foot.tagline": "We write what your product says, and hand you what you need to hold it.",
    "nav.services": "The audit",
  },
}

export default function ProductTerrainPage() {
  return <TerrainPage copy={COPY} />
}
