import type { Metadata } from "next"
import { TerrainPage, type TerrainCopy } from "@/components/terrain/terrain-page"

/**
 * THE PRODUCT — le terrain produits.
 *
 * Quatrième terrain, même gabarit que BRAND, THE ROOM et THE NAME : même
 * HTML, même CSS, même JavaScript. Seul le dictionnaire change.
 *
 * Distinct de BRAND, et la distinction tient : une marque se juge sur ce
 * qu'elle refuse, un produit sur ce qu'il a fallu accepter pour le faire
 * ainsi. Le premier vend une position, le second une intention de
 * conception.
 */

export const metadata: Metadata = {
  title: "THE PRODUCT — L'architecture narrative pour les produits",
  description:
    "Votre produit est bon, mais en rayon il devient une ligne de caractéristiques. L'architecture narrative dit ce qu'il raconte aujourd'hui et donne les mouvements qui le sortent de la comparaison.",
}

const COPY: TerrainCopy = {
  slug: "the-product",
  wordmark: "THE PRODUCT",
  fr: {
    "case.normLabel": "Ce que fait le secteur",
    "case.refuseLabel": "Ce qu'elle a fait",
    "case.resultLabel": "Ce que ça a donné",
    "case.eyebrow": "Ce que ça donne, ailleurs",
    "case.title": "Trois produits qui ont tranché.",
    "case.lead": "Aucun n'a été construit par nous. Tous les trois ont fait, à leur échelle, ce que cette Architecture fait pour le vôtre.",
    "case.1.name": "Patagonia",
    "case.1.norm": "Un jour de Black Friday, le jour le plus lucratif de l'année pour la plupart des marques, la plupart des enseignes maximisent leurs promotions.",
    "case.1.refuse": "Patagonia a publié une pleine page dans le New York Times avec un message simple : n'achetez pas cette veste. L'idée était de rappeler le coût environnemental de chaque achat, au risque direct de décourager des ventes le jour où le plus de monde regarde.",
    "case.1.body": "Le résultat a été l'inverse d'un aveu de faiblesse : la marque est devenue la référence de celles et ceux qui cherchent un achat qui a du sens, précisément parce qu'elle a semblé prête à vendre moins pour rester cohérente avec ce qu'elle défend.",
    "case.2.name": "Aesop",
    "case.2.norm": "Le secteur de la cosmétique vit au rythme des promotions saisonnières et du renouvellement permanent du packaging pour paraître neuf.",
    "case.2.refuse": "Aesop a choisi l'inverse depuis sa création : le même flacon ambré minimaliste, sans aucune remise, dans chaque boutique du monde, année après année. Cette constance obstinée va à contre-courant d'un secteur qui change sans cesse.",
    "case.2.body": "Elle est devenue la preuve de sérieux qui justifie un prix nettement supérieur à la moyenne du marché. On n'achète pas seulement un soin — on achète une marque qui n'a jamais eu besoin de crier pour se faire remarquer.",
    "case.3.name": "Liquid Death",
    "case.3.norm": "Le rayon eau en bouteille est saturé de packaging bleu, de mentions de pureté et de minéraux, tous vantant à peu près la même chose.",
    "case.3.refuse": "Liquid Death a habillé de l'eau plate en canette dans une esthétique heavy metal complète — typographie gothique, humour noir, slogans provocateurs. Le risque était de paraître absurde plutôt que sérieux, sur un produit qui n'a objectivement rien d'un death metal.",
    "case.3.body": "C'est précisément cette absurdité assumée qui a fait sa notoriété : dans un rayon où tout se ressemble, une canette qui ne ressemble à rien d'autre devient, presque par accident, le produit dont tout le monde parle.",
    "tour.out": "Vous avez déjà tout ce qu'il faut. Ce qui manque, c'est une identité pour le rendre visible.",
    "mq.1": "Objets",
    "mq.2": "Applications",
    "mq.3": "Collections",
    "mq.4": "Éditions",
    "mq.5": "Instruments",
    "mq.6": "Machines",
    "hero.tag": "Un produit moins bien fait<br/><b>se vend deux fois plus cher que le vôtre.</b>",
    "man.eyebrow": "Le constat",
    "man.body": "<b>Un produit moins bien fait que le vôtre se vend deux fois plus cher.</b> Il n'est pas mieux conçu. Il ne dure pas plus longtemps. Il se raconte mieux — et l'acheteur, qui ne peut pas démonter l'objet en rayon, n'a que ça pour décider.",
    "man.body2": "Le vôtre est bien fait, ceux qui l'utilisent le gardent. Mais en rayon il devient une ligne de caractéristiques à côté d'une autre, parce que rien ne dit pourquoi il a été fait comme ça. <em>Votre intention n'a jamais été écrite.</em>",
    "focus.eyebrow": "La différence",
    "focus.title": "Lister, ou raconter.",
    "focus.lead": "Le même produit, deux réalités. Prenez la poignée et tirez : à gauche on liste des caractéristiques, à droite l'intention est écrite et chaque détail la confirme.",
    "focus.bad.tag": "Un produit qui liste",
    "focus.bad.big": "Une suite de caractéristiques. L'acheteur compare des chiffres, donc il compare des prix.",
    "focus.good.tag": "Un produit qui se raconte",
    "focus.good.big": "L'intention est écrite. Chaque choix de conception devient un argument au lieu d'une ligne de spec. Tout se tient, sans se répéter.",
    "faq.title": "Ce que les fabricants nous demandent.",
    "st.1.t": "On lit ce que le produit dit de lui-même.",
    "st.1.d": "La page produit, la fiche, l'emballage, les photos, la notice, et ce que les acheteurs en disent dans leurs avis. Le récit est déjà là, dans vos choix de conception ; personne ne l'a formulé.",
    "st.1.b1": "Questionnaire d'entrée adapté à votre produit",
    "st.1.b2": "Lecture de tout ce qui accompagne le produit aujourd'hui",
    "st.2.t": "On cartographie le rayon.",
    "st.2.d": "Trois à cinq produits concurrents, leur promesse exacte, et l'argument que chacun met en avant. C'est là qu'apparaît l'angle que personne ne prend — et c'est souvent celui de votre conception.",
    "st.2.b1": "Autopsie de la promesse de chaque produit",
    "st.2.b2": "L'argument que trois d'entre eux revendiquent déjà",
    "st.2.b3": "L'angle libre, et pourquoi il est libre",
    "st.3.t": "On dit ce que votre produit raconte.",
    "st.3.d": "Pas ce qu'il fait : ce qu'il signifie pour celui qui l'achète. L'écart entre les deux explique en général pourquoi on le compare au prix.",
    "st.3.b1": "L'intention réelle, sous les caractéristiques",
    "st.3.b2": "Ce qui vous rend interchangeable",
    "st.3.b3": "Ce que votre packaging dit avant vous",
    "st.4.t": "On donne les mouvements.",
    "st.4.d": "Trois à cinq mouvements, dans l'ordre de priorité, avec ce que chacun coûte et ce qu'il débloque.",
    "st.4.b1": "Les mouvements à faire, hiérarchisés",
    "st.4.b2": "Ceux à refuser, et pourquoi",
    "st.4.b3": "Ce qu'il faut cesser de dire, et pourquoi",
    "st.5.t": "Nous vous laissons le document.",
    "st.5.d": "Vingt à trente pages, écrites à la main, utilisables par votre équipe produit comme par vos revendeurs.",
    "st.5.b1": "Un document relisable et transmissible",
    "st.5.b2": "Aucun abonnement, aucune dépendance",
    "st.title": "On lit, on compare, on tranche.",
    "st.eyebrow": "L'Architecture · la méthode S.T.R.A.W.",
    "st.hint": "Faites glisser",
    "hero.kicker": "Architecture narrative · Produits",
    "who.title": "Le studio qui écrit votre produit.",
    "who.body2": "Pas d'équipe, pas de sous-traitance, pas d'intermédiaire. Ceux qui lisent votre produit sont ceux qui écrivent le document.",
    "cta.title": "Racontez-nous votre produit.",
    "contact.title": "Votre produit a déjà tout. Écrivons-le.",
    "f.place": "Nom du produit",
    "f.type": "Type de produit",
    "f.opt.r": "Objet physique",
    "f.opt.b": "Produit numérique",
    "f.opt.c": "Collection ou gamme",
    "f.opt.cs": "Autre",
    "f.message": "Où en êtes-vous aujourd'hui, et qu'aimeriez-vous qu'on comprenne de votre produit ?",
    "f.required": "Champ requis",
    "foot.tagline": "On écrit ce que votre produit raconte, et on vous donne de quoi le tenir.",
    "nav.services": "L'Architecture",
    "for.yes.1": "Vous fabriquez ou éditez un produit bien fait, que ceux qui l'utilisent gardent.",
    "for.no.1": "Vous cherchez un redesign de packaging ou d'emballage.",
    "for.yes.2": "En rayon ou sur une page d'achat, il devient une ligne de caractéristiques à côté d'une autre.",
    "for.no.2": "Vous n'avez pas encore de produit commercialisé.",
    "for.yes.3": "Vous voulez dire pourquoi il est fait ainsi, et que vos revendeurs le disent avec vos mots.",
    "for.no.3": "Vous voulez qu'on rédige vos fiches une à une, sans fixer d'abord la position.",
    "faq.1.q": "Pourquoi pas une agence packaging ?",
    "faq.1.a": "Une agence packaging redessine la boîte. Elle ne décide pas ce que le produit refuse d'être. Vous repartirez avec un joli emballage qui dit la même chose que les quatre autres du rayon, et il faudra recommencer à la gamme suivante. Ici vous repartez avec la doctrine qui rend chaque emballage à venir évident à écrire.",
    "faq.2.q": "Et si je vends via des revendeurs ?",
    "faq.2.a": "C'est précisément le cas où ça compte le plus. Un revendeur présente votre produit avec ses mots à lui, faute d'avoir les vôtres. Les playbooks contiennent la fiche que vous lui remettez, les trois arguments à tenir, et la ligne à ne jamais concéder sur le prix.",
    "faq.3.q": "J'ai plusieurs produits, ça marche ?",
    "faq.3.a": "L'Architecture porte sur la maison, pas sur une référence. Le lexique, la position et les playbooks valent pour toute la gamme. Le diagnostic, lui, se concentre sur le produit qui porte le plus de chiffre : c'est celui qui révèle vos arbitrages.",
    "faq.7.q": "Et si le diagnostic ne m'apprend rien ?",
    "faq.7.a": "Alors nous vous le disons, et c'est une réponse en soi : l'intention est déjà lisible, n'y touchez pas. Ça arrive rarement : ce qui vous semble évident dans vos choix de conception n'apparaît presque jamais sur la page produit ni sur l'emballage, et c'est cet écart que le document mesure. Dans ce cas, vous aurez économisé la refonte d'emballage que vous envisagiez.",
    "faq.8.q": "Qu'est-ce que je garde à la fin ?",
    "faq.8.a": "Tout, sans licence ni abonnement. Le document est à vous, avec un droit d'usage commercial illimité et perpétuel : la position de votre produit, les textes de fiche, la réponse type aux avis, et le bloc à coller dans votre outil IA. Vos équipes l'appliquent sans nous, et vos revendeurs aussi.",
    "cta.lead": "2 900 €, livré en trois semaines, ou remboursé. Un document écrit pour votre produit, à vous pour toujours.",
  },
  en: {
    "case.normLabel": "What the industry does",
    "case.refuseLabel": "What it did",
    "case.resultLabel": "What it earned",
    "case.eyebrow": "What it looks like elsewhere",
    "case.title": "Three products that decided.",
    "case.lead": "None of them were built by us. All three did, at their scale, what this Architecture does for yours.",
    "case.1.name": "Patagonia",
    "case.1.norm": "On Black Friday, the most lucrative day of the year for most brands, most chains maximise their promotions.",
    "case.1.refuse": "Patagonia ran a full page in the New York Times with a simple message: don't buy this jacket. The point was to name the environmental cost of every purchase, at the direct risk of discouraging sales on the one day most people are watching.",
    "case.1.body": "The result was the opposite of an admission of weakness: the brand became the reference for anyone looking for a purchase that means something, precisely because it looked willing to sell less to stay consistent with what it stands for.",
    "case.2.name": "Aesop",
    "case.2.norm": "The cosmetics industry runs on seasonal promotions and constant packaging refreshes to look new.",
    "case.2.refuse": "Aesop chose the opposite from day one: the same minimalist amber bottle, with no discounts ever, in every store worldwide, year after year. That stubborn consistency runs against an industry that never stops changing.",
    "case.2.body": "It became the proof of seriousness that justifies a price well above the market average. You're not just buying a skincare product — you're buying a brand that never needed to shout to be noticed.",
    "case.3.name": "Liquid Death",
    "case.3.norm": "The bottled water aisle is saturated with blue packaging, claims of purity and minerals, all promising roughly the same thing.",
    "case.3.refuse": "Liquid Death dressed still water in a can with a full heavy-metal aesthetic — gothic typography, dark humour, provocative taglines. The risk was looking absurd rather than serious, on a product that objectively has nothing to do with death metal.",
    "case.3.body": "That embraced absurdity is exactly what built its notoriety: in an aisle where everything looks the same, a can that looks like nothing else becomes, almost by accident, the product everyone talks about.",
    "tour.out": "You already have everything you need. What is missing is an identity to make it visible.",
    "mq.1": "Objects",
    "mq.2": "Apps",
    "mq.3": "Collections",
    "mq.4": "Editions",
    "mq.5": "Instruments",
    "mq.6": "Machines",
    "hero.tag": "A worse-made product<br/><b>sells for twice the price of yours.</b>",
    "man.eyebrow": "The finding",
    "man.body": "<b>A product made worse than yours sells for twice the price.</b> It is not better designed. It does not last longer. It is better told — and the buyer, who cannot take the object apart on the shelf, has nothing else to decide on.",
    "man.body2": "Yours is well made, the people who use it keep it. But on a shelf it becomes one line of specs next to another, because nothing says why it was made this way. <em>Your intent has never been written.</em>",
    "focus.eyebrow": "The difference",
    "focus.title": "Listing, or telling.",
    "focus.lead": "The same product, two realities. Take the handle and pull.",
    "focus.bad.tag": "A product that lists",
    "focus.bad.big": "A run of specifications. The buyer compares numbers, so the buyer compares prices.",
    "focus.good.tag": "A product that tells its story",
    "focus.good.big": "The intent is written. Every design choice becomes an argument instead of a spec line.",
    "faq.title": "What makers ask us.",
    "st.1.t": "We read what the product says about itself.",
    "st.1.d": "The product page, the spec sheet, the packaging, the manual — and what buyers say in their reviews.",
    "st.1.b1": "An entry questionnaire matched to your product",
    "st.1.b2": "A reading of everything that surrounds it",
    "st.2.t": "We map the shelf.",
    "st.2.d": "Three to five competing products, their exact promise, and the argument each one leads with.",
    "st.2.b1": "An autopsy of each competitor's promise",
    "st.2.b2": "The argument three of them claim",
    "st.2.b3": "The angle nobody takes",
    "st.3.t": "We name its intent.",
    "st.3.d": "Not what it does: what it means to the person buying it. The gap explains why it gets compared on price.",
    "st.3.b1": "The real intent, under the specs",
    "st.3.b2": "What makes you interchangeable",
    "st.3.b3": "What your packaging says before you do",
    "st.4.t": "We hand over the moves.",
    "st.4.d": "Three to five moves, ranked, with what each one costs and unlocks.",
    "st.4.b1": "The moves to make, in order",
    "st.4.b2": "The ones to refuse, and why",
    "st.4.b3": "What to stop saying",
    "st.5.t": "We leave you the document.",
    "st.5.d": "Twenty to thirty pages, written by hand, usable by your product team and your resellers alike.",
    "st.5.b1": "A document you can re-read and pass on",
    "st.5.b2": "No subscription, no dependency",
    "st.title": "We read, we compare, we settle.",
    "st.eyebrow": "The Architecture · the S.T.R.A.W. method",
    "st.hint": "Drag across",
    "hero.kicker": "Narrative architecture · Products",
    "who.title": "The studio that writes your product.",
    "who.body2": "No team, no subcontracting, no middleman. The people who read your product are the people who write the document.",
    "cta.title": "Tell us about your product.",
    "contact.title": "Your product already has everything. Let's write it.",
    "f.place": "Product name",
    "f.type": "Type of product",
    "f.opt.r": "Physical object",
    "f.opt.b": "Digital product",
    "f.opt.c": "Collection or range",
    "f.opt.cs": "Other",
    "f.message": "Where are you today, and what would you like people to understand about your product?",
    "f.required": "Required field",
    "foot.tagline": "We write what your product says, and hand you what you need to hold it.",
    "nav.services": "The Architecture",
    "for.yes.1": "You make or publish a well-made product that the people who use it keep.",
    "for.no.1": "You are looking for a packaging redesign.",
    "for.yes.2": "On a shelf or a buying page it becomes one line of specifications next to another.",
    "for.no.2": "You do not have a product on the market yet.",
    "for.yes.3": "You want to say why it is made the way it is, and have your resellers say it in your words.",
    "for.no.3": "You want your product sheets written one by one, without fixing the position first.",
    "faq.1.q": "Why not a packaging agency?",
    "faq.1.a": "A packaging agency redraws the box. It does not decide what the product refuses to be. You would leave with a handsome pack that says the same thing as the four others on the shelf, and start again with the next range. Here you leave with the doctrine that makes every future pack obvious to write.",
    "faq.2.q": "What if I sell through resellers?",
    "faq.2.a": "That is exactly where it matters most. A reseller presents your product in their own words because they do not have yours. The playbooks hold the sheet you hand them, the three arguments to hold, and the line never to concede on price.",
    "faq.3.q": "I have several products. Does it work?",
    "faq.3.a": "The Architecture covers the house, not a single reference. The lexicon, the position and the playbooks apply to the whole range. The diagnosis concentrates on the product that carries the most revenue: that is the one that reveals your trade-offs.",
    "faq.7.q": "What if the diagnosis teaches me nothing?",
    "faq.7.a": "Then we tell you so, and that is an answer in itself: the intent already reads, leave it alone. It happens rarely: what seems obvious to you in your design choices almost never shows up on the product page or the packaging, and that gap is what the document measures. In that case you will have saved the packaging redesign you were considering.",
    "faq.8.q": "What do I keep at the end?",
    "faq.8.a": "Everything, with no licence or subscription. The document is yours, with unlimited and perpetual commercial use: your product's position, the product-sheet copy, the standard reply to reviews, and the block to paste into your AI tool. Your teams apply it without us, and so do your resellers.",
    "cta.lead": "€2,900, delivered in three weeks, or refunded. A document written for your product, yours for good.",
  },
}

export default function ProductTerrainPage() {
  return <TerrainPage copy={COPY} />
}
