import type { Metadata } from "next"
import { TerrainPage, type TerrainCopy } from "@/components/terrain/terrain-page"

/**
 * THE PRODUCT — le terrain produits.
 *
 * Quatrième terrain, même gabarit que BRAND, THE ROOM et THE NAME : même
 * HTML, même CSS, même JavaScript. Seul le dictionnaire change.
 *
 * Distinct de BRAND, et la distinction tient : une marque se juge sur ce
 * qu'elle refuse, un produit sur ce qu'il a fallu accepter pour le faire
 * ainsi. Le premier vend une position, le second une intention de
 * conception.
 */

export const metadata: Metadata = {
  title: "THE PRODUCT — L'audit narratif pour les produits",
  description:
    "Votre produit est bon, mais en rayon il devient une ligne de caractéristiques. L'audit narratif dit ce qu'il raconte aujourd'hui et donne les mouvements qui le sortent de la comparaison.",
}

const COPY: TerrainCopy = {
  wordmark: "THE PRODUCT",
  fr: {
    "hero.kicker": "Audit narratif · Produits",
    "hero.tag": "Votre produit est bon. Ce qu'il raconte, personne ne l'a écrit.",
    "mq.1": "Objets",
    "mq.2": "Applications",
    "mq.3": "Collections",
    "mq.4": "Éditions",
    "mq.5": "Instruments",
    "mq.6": "Machines",
    "man.eyebrow": "Le constat",
    "man.body": "Votre produit est bien fait. Ceux qui l'utilisent le gardent. <b>Et pourtant</b>, en rayon ou sur une page de comparaison, il devient une ligne de caractéristiques à côté d'une autre — parce que rien ne dit pourquoi il a été fait comme ça. Pendant ce temps, un produit moins bon se vend deux fois plus cher. Il n'est pas mieux conçu. <b>Il se raconte mieux.</b>",
    "man.body2": "Vous n'avez pas un problème de fiche technique. Vous avez un problème d'intention. Un produit porte déjà un récit — une contrainte acceptée, un arbitrage, un refus de faire comme les autres. <b>Le vôtre n'a jamais été écrit.</b>",
    "st.eyebrow": "L'audit",
    "st.title": "Sept jours, cinq blocs.",
    "st.1.t": "On lit ce que le produit dit de lui-même.",
    "st.1.d": "La page produit, la fiche, l'emballage, les photos, la notice, et ce que les acheteurs en disent dans leurs avis. Le récit est déjà là, dans vos choix de conception ; personne ne l'a formulé.",
    "st.1.b1": "Questionnaire d'entrée adapté à votre produit",
    "st.1.b2": "Lecture de tout ce qui accompagne le produit aujourd'hui",
    "st.2.t": "On cartographie le rayon.",
    "st.2.d": "Trois à cinq produits concurrents, leur promesse exacte, et l'argument que chacun met en avant. C'est là qu'apparaît l'angle que personne ne prend — et c'est souvent celui de votre conception.",
    "st.2.b1": "Autopsie de la promesse de chaque produit",
    "st.2.b2": "L'argument que trois d'entre eux revendiquent déjà",
    "st.2.b3": "L'angle libre, et pourquoi il est libre",
    "st.3.t": "On dit ce que votre produit raconte.",
    "st.3.d": "Pas ce qu'il fait : ce qu'il signifie pour celui qui l'achète. L'écart entre les deux explique en général pourquoi on le compare au prix.",
    "st.3.b1": "L'intention réelle, sous les caractéristiques",
    "st.3.b2": "Ce qui vous rend interchangeable",
    "st.3.b3": "Ce que votre packaging dit avant vous",
    "st.4.t": "On donne les mouvements.",
    "st.4.d": "Trois à cinq mouvements, dans l'ordre de priorité, avec ce que chacun coûte et ce qu'il débloque.",
    "st.4.b1": "Les mouvements à faire, hiérarchisés",
    "st.4.b2": "Ceux à refuser, et pourquoi",
    "st.4.b3": "Ce qu'il faut cesser de dire, et pourquoi",
    "focus.lead": "Le même produit, deux réalités. Prenez la poignée et tirez : à gauche on liste des caractéristiques, à droite l'intention est écrite et chaque détail la confirme.",
    "focus.bad.tag": "Un produit qui liste",
    "focus.good.tag": "Un produit qui se raconte",
    "focus.good.big": "L'intention est écrite. Chaque choix de conception devient un argument au lieu d'une ligne de spec. Tout se tient, sans se répéter.",
    "stat.3.l": "Seul document, pour toute la gamme",
    "price.a.d": "Elle exécute à votre place. Elle sait ce que votre produit raconte, vous non. Au bout de deux ans : environ 30 000 € dépensés, et rien qui vous appartienne.",
    "price.b.d": "On lit votre produit comme le fait l'acheteur : ce qu'il raconte aujourd'hui, ce qu'on en retient, et les mouvements qui changent ça. Un document de vingt à trente pages, livré en sept jours. Le même audit que pour une marque, un lieu ou un nom.",
    "price.after": "Ensuite, si vous voulez qu'on écrive le récit complet et qu'on livre les vingt pièces qui le tiennent : l'architecture narrative, 4 500 €.",
    "who.title": "Le studio qui écrit votre produit.",
    "who.body2": "Pas d'équipe, pas de sous-traitance, pas d'intermédiaire. Ceux qui lisent votre produit sont ceux qui écrivent le document.",
    "faq.3.a": "Quelques heures en tout. Un questionnaire d'entrée, un échange avec vous, et la remise du document. Le reste du travail se fait sans vous mobiliser.",
    "faq.4.a": "C'est prévu. Le document est écrit pour être appliqué par quelqu'un qui n'a pas conçu le produit : ce qu'on revendique, ce qu'on refuse, avec quels mots.",
    "cta.title": "Racontez-nous votre produit.",
    "cta.lead": "Vingt minutes suffisent pour savoir si votre produit a de quoi être écrit. Nous prenons peu de projets à la fois, et nous répondons nous-mêmes.",
    "contact.title": "Votre produit a déjà tout. Écrivons-le.",
    "f.place": "Nom du produit",
    "f.type": "Type de produit",
    "f.opt.r": "Objet physique",
    "f.opt.b": "Produit numérique",
    "f.opt.c": "Collection ou gamme",
    "f.opt.cs": "Autre",
    "f.message": "Où en êtes-vous aujourd'hui, et qu'aimeriez-vous qu'on comprenne de votre produit ?",
    "f.required": "Champ requis",
    "foot.tagline": "On écrit ce que votre produit raconte, et on vous donne de quoi le tenir.",
    "nav.services": "L'audit",
  },
  en: {
    "hero.kicker": "Narrative audit · Products",
    "hero.tag": "Your product is good. What it says has never been written.",
    "mq.1": "Objects",
    "mq.2": "Apps",
    "mq.3": "Collections",
    "mq.4": "Editions",
    "mq.5": "Instruments",
    "mq.6": "Machines",
    "man.eyebrow": "The finding",
    "man.body": "Your product is well made. The people who use it keep it. <b>And yet</b>, on a shelf or a comparison page it becomes one line of specs next to another — because nothing says why it was made this way. Meanwhile a worse product sells for twice the price. It is not better designed. <b>It is better told.</b>",
    "man.body2": "You do not have a spec sheet problem. You have an intent problem. A product already carries a story — a constraint accepted, a trade-off, a refusal to do what everyone else does. <b>Yours has never been written.</b>",
    "st.eyebrow": "The audit",
    "st.title": "Seven days, five blocks.",
    "st.1.t": "We read what the product says about itself.",
    "st.1.d": "The product page, the spec sheet, the packaging, the photos, the manual, and what buyers say in their reviews. The story is already there, in your design choices; nobody has put it into words.",
    "st.1.b1": "An entry questionnaire matched to your product",
    "st.1.b2": "A reading of everything that surrounds the product today",
    "st.2.t": "We map the shelf.",
    "st.2.d": "Three to five competing products, their exact promise, and the argument each one leads with. That is where the unused angle appears — and it is often the one built into your design.",
    "st.2.b1": "An autopsy of each product's promise",
    "st.2.b2": "The argument three of them already claim",
    "st.2.b3": "The open angle, and why it is open",
    "st.3.t": "We state what your product says.",
    "st.3.d": "Not what it does: what it means to the person buying it. The gap between the two usually explains why it gets compared on price.",
    "st.3.b1": "The real intent, under the specs",
    "st.3.b2": "What makes you interchangeable",
    "st.3.b3": "What your packaging says before you do",
    "st.4.t": "We hand over the moves.",
    "st.4.d": "Three to five moves, in priority order, with what each one costs and what it unlocks.",
    "st.4.b1": "The moves to make, ranked",
    "st.4.b2": "The ones to refuse, and why",
    "st.4.b3": "What to stop saying, and why",
    "focus.lead": "The same product, two realities. Take the handle and pull: on the left, a list of specs; on the right, the intent is written and every detail confirms it.",
    "focus.bad.tag": "A product that lists",
    "focus.good.tag": "A product that tells its story",
    "focus.good.big": "The intent is written. Every design choice becomes an argument instead of a spec line. It all holds together, without repeating itself.",
    "stat.3.l": "Single document, for the whole range",
    "price.a.d": "It executes in your place. It knows what your product says, you do not. After two years: roughly 30,000 € spent, and nothing that belongs to you.",
    "price.b.d": "We read your product the way the buyer does: what it says today, what people keep of it, and the moves that change that. A twenty to thirty page document, delivered in seven days. The same audit as for a brand, a venue or a name.",
    "price.after": "Then, if you want the full story written and the twenty pieces that hold it: the narrative architecture, 4,500 €.",
    "who.title": "The studio that writes your product.",
    "who.body2": "No team, no subcontracting, no middleman. The people who read your product are the people who write the document.",
    "faq.3.a": "A few hours in total. An entry questionnaire, a conversation with you, and the delivery. The rest of the work happens without taking your time.",
    "faq.4.a": "That is accounted for. The document is written to be applied by someone who did not design the product: what you claim, what you refuse, in which words.",
    "cta.title": "Tell us about your product.",
    "cta.lead": "Twenty minutes is enough to know whether your product has something worth writing. We take on few projects at a time, and we answer ourselves.",
    "contact.title": "Your product already has everything. Let's write it.",
    "f.place": "Product name",
    "f.type": "Type of product",
    "f.opt.r": "Physical object",
    "f.opt.b": "Digital product",
    "f.opt.c": "Collection or range",
    "f.opt.cs": "Other",
    "f.message": "Where are you today, and what would you like people to understand about your product?",
    "f.required": "Required field",
    "foot.tagline": "We write what your product says, and hand you what you need to hold it.",
    "nav.services": "The audit",
  },
}

export default function ProductTerrainPage() {
  return <TerrainPage copy={COPY} />
}
